/**
 * generated by Xtext 2.22.0
 */
package ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.impl;

import ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.Hop;
import ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.PerspectiveDSLPackage;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Hop</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.impl.HopImpl#getHopElement <em>Hop Element</em>}</li>
 *   <li>{@link ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.impl.HopImpl#getFromGetHop <em>From Get Hop</em>}</li>
 * </ul>
 *
 * @generated
 */
public class HopImpl extends MinimalEObjectImpl.Container implements Hop
{
  /**
   * The default value of the '{@link #getHopElement() <em>Hop Element</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getHopElement()
   * @generated
   * @ordered
   */
  protected static final String HOP_ELEMENT_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getHopElement() <em>Hop Element</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getHopElement()
   * @generated
   * @ordered
   */
  protected String hopElement = HOP_ELEMENT_EDEFAULT;

  /**
   * The default value of the '{@link #getFromGetHop() <em>From Get Hop</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFromGetHop()
   * @generated
   * @ordered
   */
  protected static final String FROM_GET_HOP_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getFromGetHop() <em>From Get Hop</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFromGetHop()
   * @generated
   * @ordered
   */
  protected String fromGetHop = FROM_GET_HOP_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected HopImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return PerspectiveDSLPackage.Literals.HOP;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getHopElement()
  {
    return hopElement;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setHopElement(String newHopElement)
  {
    String oldHopElement = hopElement;
    hopElement = newHopElement;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PerspectiveDSLPackage.HOP__HOP_ELEMENT, oldHopElement, hopElement));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getFromGetHop()
  {
    return fromGetHop;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setFromGetHop(String newFromGetHop)
  {
    String oldFromGetHop = fromGetHop;
    fromGetHop = newFromGetHop;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PerspectiveDSLPackage.HOP__FROM_GET_HOP, oldFromGetHop, fromGetHop));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case PerspectiveDSLPackage.HOP__HOP_ELEMENT:
        return getHopElement();
      case PerspectiveDSLPackage.HOP__FROM_GET_HOP:
        return getFromGetHop();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case PerspectiveDSLPackage.HOP__HOP_ELEMENT:
        setHopElement((String)newValue);
        return;
      case PerspectiveDSLPackage.HOP__FROM_GET_HOP:
        setFromGetHop((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case PerspectiveDSLPackage.HOP__HOP_ELEMENT:
        setHopElement(HOP_ELEMENT_EDEFAULT);
        return;
      case PerspectiveDSLPackage.HOP__FROM_GET_HOP:
        setFromGetHop(FROM_GET_HOP_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case PerspectiveDSLPackage.HOP__HOP_ELEMENT:
        return HOP_ELEMENT_EDEFAULT == null ? hopElement != null : !HOP_ELEMENT_EDEFAULT.equals(hopElement);
      case PerspectiveDSLPackage.HOP__FROM_GET_HOP:
        return FROM_GET_HOP_EDEFAULT == null ? fromGetHop != null : !FROM_GET_HOP_EDEFAULT.equals(fromGetHop);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (hopElement: ");
    result.append(hopElement);
    result.append(", fromGetHop: ");
    result.append(fromGetHop);
    result.append(')');
    return result.toString();
  }

} //HopImpl
