/**
 * generated by Xtext 2.22.0
 */
package ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.impl;

import ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.Language;
import ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.PerspectiveDSLPackage;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Language</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.impl.LanguageImpl#getName <em>Name</em>}</li>
 *   <li>{@link ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.impl.LanguageImpl#getRootPackage <em>Root Package</em>}</li>
 *   <li>{@link ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.impl.LanguageImpl#getPackageClassName <em>Package Class Name</em>}</li>
 *   <li>{@link ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.impl.LanguageImpl#getRoleName <em>Role Name</em>}</li>
 * </ul>
 *
 * @generated
 */
public class LanguageImpl extends MinimalEObjectImpl.Container implements Language
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The default value of the '{@link #getRootPackage() <em>Root Package</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRootPackage()
   * @generated
   * @ordered
   */
  protected static final String ROOT_PACKAGE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getRootPackage() <em>Root Package</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRootPackage()
   * @generated
   * @ordered
   */
  protected String rootPackage = ROOT_PACKAGE_EDEFAULT;

  /**
   * The default value of the '{@link #getPackageClassName() <em>Package Class Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPackageClassName()
   * @generated
   * @ordered
   */
  protected static final String PACKAGE_CLASS_NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getPackageClassName() <em>Package Class Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPackageClassName()
   * @generated
   * @ordered
   */
  protected String packageClassName = PACKAGE_CLASS_NAME_EDEFAULT;

  /**
   * The default value of the '{@link #getRoleName() <em>Role Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRoleName()
   * @generated
   * @ordered
   */
  protected static final String ROLE_NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getRoleName() <em>Role Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRoleName()
   * @generated
   * @ordered
   */
  protected String roleName = ROLE_NAME_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected LanguageImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return PerspectiveDSLPackage.Literals.LANGUAGE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PerspectiveDSLPackage.LANGUAGE__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getRootPackage()
  {
    return rootPackage;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setRootPackage(String newRootPackage)
  {
    String oldRootPackage = rootPackage;
    rootPackage = newRootPackage;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PerspectiveDSLPackage.LANGUAGE__ROOT_PACKAGE, oldRootPackage, rootPackage));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getPackageClassName()
  {
    return packageClassName;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setPackageClassName(String newPackageClassName)
  {
    String oldPackageClassName = packageClassName;
    packageClassName = newPackageClassName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PerspectiveDSLPackage.LANGUAGE__PACKAGE_CLASS_NAME, oldPackageClassName, packageClassName));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getRoleName()
  {
    return roleName;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setRoleName(String newRoleName)
  {
    String oldRoleName = roleName;
    roleName = newRoleName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PerspectiveDSLPackage.LANGUAGE__ROLE_NAME, oldRoleName, roleName));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case PerspectiveDSLPackage.LANGUAGE__NAME:
        return getName();
      case PerspectiveDSLPackage.LANGUAGE__ROOT_PACKAGE:
        return getRootPackage();
      case PerspectiveDSLPackage.LANGUAGE__PACKAGE_CLASS_NAME:
        return getPackageClassName();
      case PerspectiveDSLPackage.LANGUAGE__ROLE_NAME:
        return getRoleName();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case PerspectiveDSLPackage.LANGUAGE__NAME:
        setName((String)newValue);
        return;
      case PerspectiveDSLPackage.LANGUAGE__ROOT_PACKAGE:
        setRootPackage((String)newValue);
        return;
      case PerspectiveDSLPackage.LANGUAGE__PACKAGE_CLASS_NAME:
        setPackageClassName((String)newValue);
        return;
      case PerspectiveDSLPackage.LANGUAGE__ROLE_NAME:
        setRoleName((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case PerspectiveDSLPackage.LANGUAGE__NAME:
        setName(NAME_EDEFAULT);
        return;
      case PerspectiveDSLPackage.LANGUAGE__ROOT_PACKAGE:
        setRootPackage(ROOT_PACKAGE_EDEFAULT);
        return;
      case PerspectiveDSLPackage.LANGUAGE__PACKAGE_CLASS_NAME:
        setPackageClassName(PACKAGE_CLASS_NAME_EDEFAULT);
        return;
      case PerspectiveDSLPackage.LANGUAGE__ROLE_NAME:
        setRoleName(ROLE_NAME_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case PerspectiveDSLPackage.LANGUAGE__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case PerspectiveDSLPackage.LANGUAGE__ROOT_PACKAGE:
        return ROOT_PACKAGE_EDEFAULT == null ? rootPackage != null : !ROOT_PACKAGE_EDEFAULT.equals(rootPackage);
      case PerspectiveDSLPackage.LANGUAGE__PACKAGE_CLASS_NAME:
        return PACKAGE_CLASS_NAME_EDEFAULT == null ? packageClassName != null : !PACKAGE_CLASS_NAME_EDEFAULT.equals(packageClassName);
      case PerspectiveDSLPackage.LANGUAGE__ROLE_NAME:
        return ROLE_NAME_EDEFAULT == null ? roleName != null : !ROLE_NAME_EDEFAULT.equals(roleName);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(", rootPackage: ");
    result.append(rootPackage);
    result.append(", packageClassName: ");
    result.append(packageClassName);
    result.append(", roleName: ");
    result.append(roleName);
    result.append(')');
    return result.toString();
  }

} //LanguageImpl
