/**
 * generated by Xtext 2.22.0
 */
package ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.impl;

import ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.NestedMapping;
import ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.PerspectiveDSLPackage;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Nested Mapping</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.impl.NestedMappingImpl#getName <em>Name</em>}</li>
 *   <li>{@link ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.impl.NestedMappingImpl#getFromElementName <em>From Element Name</em>}</li>
 *   <li>{@link ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.impl.NestedMappingImpl#getFromRoleName <em>From Role Name</em>}</li>
 *   <li>{@link ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.impl.NestedMappingImpl#getToElementName <em>To Element Name</em>}</li>
 *   <li>{@link ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.impl.NestedMappingImpl#getToRoleName <em>To Role Name</em>}</li>
 * </ul>
 *
 * @generated
 */
public class NestedMappingImpl extends MinimalEObjectImpl.Container implements NestedMapping
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The default value of the '{@link #getFromElementName() <em>From Element Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFromElementName()
   * @generated
   * @ordered
   */
  protected static final String FROM_ELEMENT_NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getFromElementName() <em>From Element Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFromElementName()
   * @generated
   * @ordered
   */
  protected String fromElementName = FROM_ELEMENT_NAME_EDEFAULT;

  /**
   * The default value of the '{@link #getFromRoleName() <em>From Role Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFromRoleName()
   * @generated
   * @ordered
   */
  protected static final String FROM_ROLE_NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getFromRoleName() <em>From Role Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFromRoleName()
   * @generated
   * @ordered
   */
  protected String fromRoleName = FROM_ROLE_NAME_EDEFAULT;

  /**
   * The default value of the '{@link #getToElementName() <em>To Element Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getToElementName()
   * @generated
   * @ordered
   */
  protected static final String TO_ELEMENT_NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getToElementName() <em>To Element Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getToElementName()
   * @generated
   * @ordered
   */
  protected String toElementName = TO_ELEMENT_NAME_EDEFAULT;

  /**
   * The default value of the '{@link #getToRoleName() <em>To Role Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getToRoleName()
   * @generated
   * @ordered
   */
  protected static final String TO_ROLE_NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getToRoleName() <em>To Role Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getToRoleName()
   * @generated
   * @ordered
   */
  protected String toRoleName = TO_ROLE_NAME_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected NestedMappingImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return PerspectiveDSLPackage.Literals.NESTED_MAPPING;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PerspectiveDSLPackage.NESTED_MAPPING__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getFromElementName()
  {
    return fromElementName;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setFromElementName(String newFromElementName)
  {
    String oldFromElementName = fromElementName;
    fromElementName = newFromElementName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PerspectiveDSLPackage.NESTED_MAPPING__FROM_ELEMENT_NAME, oldFromElementName, fromElementName));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getFromRoleName()
  {
    return fromRoleName;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setFromRoleName(String newFromRoleName)
  {
    String oldFromRoleName = fromRoleName;
    fromRoleName = newFromRoleName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PerspectiveDSLPackage.NESTED_MAPPING__FROM_ROLE_NAME, oldFromRoleName, fromRoleName));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getToElementName()
  {
    return toElementName;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setToElementName(String newToElementName)
  {
    String oldToElementName = toElementName;
    toElementName = newToElementName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PerspectiveDSLPackage.NESTED_MAPPING__TO_ELEMENT_NAME, oldToElementName, toElementName));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getToRoleName()
  {
    return toRoleName;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setToRoleName(String newToRoleName)
  {
    String oldToRoleName = toRoleName;
    toRoleName = newToRoleName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PerspectiveDSLPackage.NESTED_MAPPING__TO_ROLE_NAME, oldToRoleName, toRoleName));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case PerspectiveDSLPackage.NESTED_MAPPING__NAME:
        return getName();
      case PerspectiveDSLPackage.NESTED_MAPPING__FROM_ELEMENT_NAME:
        return getFromElementName();
      case PerspectiveDSLPackage.NESTED_MAPPING__FROM_ROLE_NAME:
        return getFromRoleName();
      case PerspectiveDSLPackage.NESTED_MAPPING__TO_ELEMENT_NAME:
        return getToElementName();
      case PerspectiveDSLPackage.NESTED_MAPPING__TO_ROLE_NAME:
        return getToRoleName();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case PerspectiveDSLPackage.NESTED_MAPPING__NAME:
        setName((String)newValue);
        return;
      case PerspectiveDSLPackage.NESTED_MAPPING__FROM_ELEMENT_NAME:
        setFromElementName((String)newValue);
        return;
      case PerspectiveDSLPackage.NESTED_MAPPING__FROM_ROLE_NAME:
        setFromRoleName((String)newValue);
        return;
      case PerspectiveDSLPackage.NESTED_MAPPING__TO_ELEMENT_NAME:
        setToElementName((String)newValue);
        return;
      case PerspectiveDSLPackage.NESTED_MAPPING__TO_ROLE_NAME:
        setToRoleName((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case PerspectiveDSLPackage.NESTED_MAPPING__NAME:
        setName(NAME_EDEFAULT);
        return;
      case PerspectiveDSLPackage.NESTED_MAPPING__FROM_ELEMENT_NAME:
        setFromElementName(FROM_ELEMENT_NAME_EDEFAULT);
        return;
      case PerspectiveDSLPackage.NESTED_MAPPING__FROM_ROLE_NAME:
        setFromRoleName(FROM_ROLE_NAME_EDEFAULT);
        return;
      case PerspectiveDSLPackage.NESTED_MAPPING__TO_ELEMENT_NAME:
        setToElementName(TO_ELEMENT_NAME_EDEFAULT);
        return;
      case PerspectiveDSLPackage.NESTED_MAPPING__TO_ROLE_NAME:
        setToRoleName(TO_ROLE_NAME_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case PerspectiveDSLPackage.NESTED_MAPPING__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case PerspectiveDSLPackage.NESTED_MAPPING__FROM_ELEMENT_NAME:
        return FROM_ELEMENT_NAME_EDEFAULT == null ? fromElementName != null : !FROM_ELEMENT_NAME_EDEFAULT.equals(fromElementName);
      case PerspectiveDSLPackage.NESTED_MAPPING__FROM_ROLE_NAME:
        return FROM_ROLE_NAME_EDEFAULT == null ? fromRoleName != null : !FROM_ROLE_NAME_EDEFAULT.equals(fromRoleName);
      case PerspectiveDSLPackage.NESTED_MAPPING__TO_ELEMENT_NAME:
        return TO_ELEMENT_NAME_EDEFAULT == null ? toElementName != null : !TO_ELEMENT_NAME_EDEFAULT.equals(toElementName);
      case PerspectiveDSLPackage.NESTED_MAPPING__TO_ROLE_NAME:
        return TO_ROLE_NAME_EDEFAULT == null ? toRoleName != null : !TO_ROLE_NAME_EDEFAULT.equals(toRoleName);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(", fromElementName: ");
    result.append(fromElementName);
    result.append(", fromRoleName: ");
    result.append(fromRoleName);
    result.append(", toElementName: ");
    result.append(toElementName);
    result.append(", toRoleName: ");
    result.append(toRoleName);
    result.append(')');
    return result.toString();
  }

} //NestedMappingImpl
