/**
 * generated by Xtext 2.22.0
 */
package ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Hop</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.Hop#getHopElement <em>Hop Element</em>}</li>
 *   <li>{@link ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.Hop#getFromGetHop <em>From Get Hop</em>}</li>
 * </ul>
 *
 * @see ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.PerspectiveDSLPackage#getHop()
 * @model
 * @generated
 */
public interface Hop extends EObject
{
  /**
   * Returns the value of the '<em><b>Hop Element</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Hop Element</em>' attribute.
   * @see #setHopElement(String)
   * @see ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.PerspectiveDSLPackage#getHop_HopElement()
   * @model
   * @generated
   */
  String getHopElement();

  /**
   * Sets the value of the '{@link ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.Hop#getHopElement <em>Hop Element</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Hop Element</em>' attribute.
   * @see #getHopElement()
   * @generated
   */
  void setHopElement(String value);

  /**
   * Returns the value of the '<em><b>From Get Hop</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>From Get Hop</em>' attribute.
   * @see #setFromGetHop(String)
   * @see ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.PerspectiveDSLPackage#getHop_FromGetHop()
   * @model
   * @generated
   */
  String getFromGetHop();

  /**
   * Sets the value of the '{@link ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.Hop#getFromGetHop <em>From Get Hop</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>From Get Hop</em>' attribute.
   * @see #getFromGetHop()
   * @generated
   */
  void setFromGetHop(String value);

} // Hop
