/**
 * generated by Xtext 2.22.0
 */
package ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Intra Language Mapping</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.IntraLanguageMapping#getName <em>Name</em>}</li>
 *   <li>{@link ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.IntraLanguageMapping#isClosure <em>Closure</em>}</li>
 *   <li>{@link ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.IntraLanguageMapping#isReuse <em>Reuse</em>}</li>
 *   <li>{@link ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.IntraLanguageMapping#isIncreaseDepth <em>Increase Depth</em>}</li>
 *   <li>{@link ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.IntraLanguageMapping#isChangeModel <em>Change Model</em>}</li>
 *   <li>{@link ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.IntraLanguageMapping#getFromElement <em>From Element</em>}</li>
 *   <li>{@link ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.IntraLanguageMapping#getFromGetElement <em>From Get Element</em>}</li>
 *   <li>{@link ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.IntraLanguageMapping#getHops <em>Hops</em>}</li>
 * </ul>
 *
 * @see ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.PerspectiveDSLPackage#getIntraLanguageMapping()
 * @model
 * @generated
 */
public interface IntraLanguageMapping extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.PerspectiveDSLPackage#getIntraLanguageMapping_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.IntraLanguageMapping#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Closure</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Closure</em>' attribute.
   * @see #setClosure(boolean)
   * @see ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.PerspectiveDSLPackage#getIntraLanguageMapping_Closure()
   * @model
   * @generated
   */
  boolean isClosure();

  /**
   * Sets the value of the '{@link ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.IntraLanguageMapping#isClosure <em>Closure</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Closure</em>' attribute.
   * @see #isClosure()
   * @generated
   */
  void setClosure(boolean value);

  /**
   * Returns the value of the '<em><b>Reuse</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Reuse</em>' attribute.
   * @see #setReuse(boolean)
   * @see ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.PerspectiveDSLPackage#getIntraLanguageMapping_Reuse()
   * @model
   * @generated
   */
  boolean isReuse();

  /**
   * Sets the value of the '{@link ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.IntraLanguageMapping#isReuse <em>Reuse</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Reuse</em>' attribute.
   * @see #isReuse()
   * @generated
   */
  void setReuse(boolean value);

  /**
   * Returns the value of the '<em><b>Increase Depth</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Increase Depth</em>' attribute.
   * @see #setIncreaseDepth(boolean)
   * @see ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.PerspectiveDSLPackage#getIntraLanguageMapping_IncreaseDepth()
   * @model
   * @generated
   */
  boolean isIncreaseDepth();

  /**
   * Sets the value of the '{@link ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.IntraLanguageMapping#isIncreaseDepth <em>Increase Depth</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Increase Depth</em>' attribute.
   * @see #isIncreaseDepth()
   * @generated
   */
  void setIncreaseDepth(boolean value);

  /**
   * Returns the value of the '<em><b>Change Model</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Change Model</em>' attribute.
   * @see #setChangeModel(boolean)
   * @see ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.PerspectiveDSLPackage#getIntraLanguageMapping_ChangeModel()
   * @model
   * @generated
   */
  boolean isChangeModel();

  /**
   * Sets the value of the '{@link ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.IntraLanguageMapping#isChangeModel <em>Change Model</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Change Model</em>' attribute.
   * @see #isChangeModel()
   * @generated
   */
  void setChangeModel(boolean value);

  /**
   * Returns the value of the '<em><b>From Element</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>From Element</em>' attribute.
   * @see #setFromElement(String)
   * @see ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.PerspectiveDSLPackage#getIntraLanguageMapping_FromElement()
   * @model
   * @generated
   */
  String getFromElement();

  /**
   * Sets the value of the '{@link ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.IntraLanguageMapping#getFromElement <em>From Element</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>From Element</em>' attribute.
   * @see #getFromElement()
   * @generated
   */
  void setFromElement(String value);

  /**
   * Returns the value of the '<em><b>From Get Element</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>From Get Element</em>' attribute.
   * @see #setFromGetElement(String)
   * @see ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.PerspectiveDSLPackage#getIntraLanguageMapping_FromGetElement()
   * @model
   * @generated
   */
  String getFromGetElement();

  /**
   * Sets the value of the '{@link ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.IntraLanguageMapping#getFromGetElement <em>From Get Element</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>From Get Element</em>' attribute.
   * @see #getFromGetElement()
   * @generated
   */
  void setFromGetElement(String value);

  /**
   * Returns the value of the '<em><b>Hops</b></em>' containment reference list.
   * The list contents are of type {@link ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.Hop}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Hops</em>' containment reference list.
   * @see ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.PerspectiveDSLPackage#getIntraLanguageMapping_Hops()
   * @model containment="true"
   * @generated
   */
  EList<Hop> getHops();

} // IntraLanguageMapping
