/**
 * generated by Xtext 2.22.0
 */
package ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Language Element Mapping</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.LanguageElementMapping#getName <em>Name</em>}</li>
 *   <li>{@link ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.LanguageElementMapping#getFromCardinality <em>From Cardinality</em>}</li>
 *   <li>{@link ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.LanguageElementMapping#getToCardinality <em>To Cardinality</em>}</li>
 *   <li>{@link ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.LanguageElementMapping#getFromElement <em>From Element</em>}</li>
 *   <li>{@link ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.LanguageElementMapping#getFromRoleName <em>From Role Name</em>}</li>
 *   <li>{@link ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.LanguageElementMapping#getFromGetElement <em>From Get Element</em>}</li>
 *   <li>{@link ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.LanguageElementMapping#getToElement <em>To Element</em>}</li>
 *   <li>{@link ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.LanguageElementMapping#getToRoleName <em>To Role Name</em>}</li>
 *   <li>{@link ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.LanguageElementMapping#getToGetElement <em>To Get Element</em>}</li>
 *   <li>{@link ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.LanguageElementMapping#getNestedMappings <em>Nested Mappings</em>}</li>
 *   <li>{@link ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.LanguageElementMapping#getInterLanguageMappingEnds <em>Inter Language Mapping Ends</em>}</li>
 * </ul>
 *
 * @see ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.PerspectiveDSLPackage#getLanguageElementMapping()
 * @model
 * @generated
 */
public interface LanguageElementMapping extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.PerspectiveDSLPackage#getLanguageElementMapping_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.LanguageElementMapping#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>From Cardinality</b></em>' attribute.
   * The literals are from the enumeration {@link ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.Cardinality}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>From Cardinality</em>' attribute.
   * @see ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.Cardinality
   * @see #setFromCardinality(Cardinality)
   * @see ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.PerspectiveDSLPackage#getLanguageElementMapping_FromCardinality()
   * @model
   * @generated
   */
  Cardinality getFromCardinality();

  /**
   * Sets the value of the '{@link ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.LanguageElementMapping#getFromCardinality <em>From Cardinality</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>From Cardinality</em>' attribute.
   * @see ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.Cardinality
   * @see #getFromCardinality()
   * @generated
   */
  void setFromCardinality(Cardinality value);

  /**
   * Returns the value of the '<em><b>To Cardinality</b></em>' attribute.
   * The literals are from the enumeration {@link ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.Cardinality}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>To Cardinality</em>' attribute.
   * @see ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.Cardinality
   * @see #setToCardinality(Cardinality)
   * @see ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.PerspectiveDSLPackage#getLanguageElementMapping_ToCardinality()
   * @model
   * @generated
   */
  Cardinality getToCardinality();

  /**
   * Sets the value of the '{@link ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.LanguageElementMapping#getToCardinality <em>To Cardinality</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>To Cardinality</em>' attribute.
   * @see ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.Cardinality
   * @see #getToCardinality()
   * @generated
   */
  void setToCardinality(Cardinality value);

  /**
   * Returns the value of the '<em><b>From Element</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>From Element</em>' attribute.
   * @see #setFromElement(String)
   * @see ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.PerspectiveDSLPackage#getLanguageElementMapping_FromElement()
   * @model
   * @generated
   */
  String getFromElement();

  /**
   * Sets the value of the '{@link ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.LanguageElementMapping#getFromElement <em>From Element</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>From Element</em>' attribute.
   * @see #getFromElement()
   * @generated
   */
  void setFromElement(String value);

  /**
   * Returns the value of the '<em><b>From Role Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>From Role Name</em>' attribute.
   * @see #setFromRoleName(String)
   * @see ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.PerspectiveDSLPackage#getLanguageElementMapping_FromRoleName()
   * @model
   * @generated
   */
  String getFromRoleName();

  /**
   * Sets the value of the '{@link ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.LanguageElementMapping#getFromRoleName <em>From Role Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>From Role Name</em>' attribute.
   * @see #getFromRoleName()
   * @generated
   */
  void setFromRoleName(String value);

  /**
   * Returns the value of the '<em><b>From Get Element</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>From Get Element</em>' attribute.
   * @see #setFromGetElement(String)
   * @see ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.PerspectiveDSLPackage#getLanguageElementMapping_FromGetElement()
   * @model
   * @generated
   */
  String getFromGetElement();

  /**
   * Sets the value of the '{@link ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.LanguageElementMapping#getFromGetElement <em>From Get Element</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>From Get Element</em>' attribute.
   * @see #getFromGetElement()
   * @generated
   */
  void setFromGetElement(String value);

  /**
   * Returns the value of the '<em><b>To Element</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>To Element</em>' attribute.
   * @see #setToElement(String)
   * @see ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.PerspectiveDSLPackage#getLanguageElementMapping_ToElement()
   * @model
   * @generated
   */
  String getToElement();

  /**
   * Sets the value of the '{@link ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.LanguageElementMapping#getToElement <em>To Element</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>To Element</em>' attribute.
   * @see #getToElement()
   * @generated
   */
  void setToElement(String value);

  /**
   * Returns the value of the '<em><b>To Role Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>To Role Name</em>' attribute.
   * @see #setToRoleName(String)
   * @see ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.PerspectiveDSLPackage#getLanguageElementMapping_ToRoleName()
   * @model
   * @generated
   */
  String getToRoleName();

  /**
   * Sets the value of the '{@link ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.LanguageElementMapping#getToRoleName <em>To Role Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>To Role Name</em>' attribute.
   * @see #getToRoleName()
   * @generated
   */
  void setToRoleName(String value);

  /**
   * Returns the value of the '<em><b>To Get Element</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>To Get Element</em>' attribute.
   * @see #setToGetElement(String)
   * @see ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.PerspectiveDSLPackage#getLanguageElementMapping_ToGetElement()
   * @model
   * @generated
   */
  String getToGetElement();

  /**
   * Sets the value of the '{@link ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.LanguageElementMapping#getToGetElement <em>To Get Element</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>To Get Element</em>' attribute.
   * @see #getToGetElement()
   * @generated
   */
  void setToGetElement(String value);

  /**
   * Returns the value of the '<em><b>Nested Mappings</b></em>' containment reference list.
   * The list contents are of type {@link ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.NestedMapping}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Nested Mappings</em>' containment reference list.
   * @see ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.PerspectiveDSLPackage#getLanguageElementMapping_NestedMappings()
   * @model containment="true"
   * @generated
   */
  EList<NestedMapping> getNestedMappings();

  /**
   * Returns the value of the '<em><b>Inter Language Mapping Ends</b></em>' containment reference list.
   * The list contents are of type {@link ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.InterLanguageMappingEnd}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Inter Language Mapping Ends</em>' containment reference list.
   * @see ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.PerspectiveDSLPackage#getLanguageElementMapping_InterLanguageMappingEnds()
   * @model containment="true"
   * @generated
   */
  EList<InterLanguageMappingEnd> getInterLanguageMappingEnds();

} // LanguageElementMapping
