/**
 * generated by Xtext 2.22.0
 */
package ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Language</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.Language#getName <em>Name</em>}</li>
 *   <li>{@link ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.Language#getRootPackage <em>Root Package</em>}</li>
 *   <li>{@link ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.Language#getPackageClassName <em>Package Class Name</em>}</li>
 *   <li>{@link ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.Language#getRoleName <em>Role Name</em>}</li>
 * </ul>
 *
 * @see ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.PerspectiveDSLPackage#getLanguage()
 * @model
 * @generated
 */
public interface Language extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.PerspectiveDSLPackage#getLanguage_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.Language#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Root Package</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Root Package</em>' attribute.
   * @see #setRootPackage(String)
   * @see ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.PerspectiveDSLPackage#getLanguage_RootPackage()
   * @model
   * @generated
   */
  String getRootPackage();

  /**
   * Sets the value of the '{@link ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.Language#getRootPackage <em>Root Package</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Root Package</em>' attribute.
   * @see #getRootPackage()
   * @generated
   */
  void setRootPackage(String value);

  /**
   * Returns the value of the '<em><b>Package Class Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Package Class Name</em>' attribute.
   * @see #setPackageClassName(String)
   * @see ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.PerspectiveDSLPackage#getLanguage_PackageClassName()
   * @model
   * @generated
   */
  String getPackageClassName();

  /**
   * Sets the value of the '{@link ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.Language#getPackageClassName <em>Package Class Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Package Class Name</em>' attribute.
   * @see #getPackageClassName()
   * @generated
   */
  void setPackageClassName(String value);

  /**
   * Returns the value of the '<em><b>Role Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Role Name</em>' attribute.
   * @see #setRoleName(String)
   * @see ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.PerspectiveDSLPackage#getLanguage_RoleName()
   * @model
   * @generated
   */
  String getRoleName();

  /**
   * Sets the value of the '{@link ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.Language#getRoleName <em>Role Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Role Name</em>' attribute.
   * @see #getRoleName()
   * @generated
   */
  void setRoleName(String value);

} // Language
