/**
 * generated by Xtext 2.22.0
 */
package ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.PerspectiveDSLFactory
 * @model kind="package"
 * @generated
 */
public interface PerspectiveDSLPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "perspectiveDSL";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.mcgill.ca/sel/perspectivedsl/ca/mcgill/sel/PerspectiveDSL";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "perspectiveDSL";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  PerspectiveDSLPackage eINSTANCE = ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.impl.PerspectiveDSLPackageImpl.init();

  /**
   * The meta object id for the '{@link ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.impl.PerspectiveModelImpl <em>Perspective Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.impl.PerspectiveModelImpl
   * @see ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.impl.PerspectiveDSLPackageImpl#getPerspectiveModel()
   * @generated
   */
  int PERSPECTIVE_MODEL = 0;

  /**
   * The feature id for the '<em><b>Perspective</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERSPECTIVE_MODEL__PERSPECTIVE = 0;

  /**
   * The number of structural features of the '<em>Perspective Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERSPECTIVE_MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.impl.PerspectiveImpl <em>Perspective</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.impl.PerspectiveImpl
   * @see ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.impl.PerspectiveDSLPackageImpl#getPerspective()
   * @generated
   */
  int PERSPECTIVE = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERSPECTIVE__NAME = 0;

  /**
   * The feature id for the '<em><b>Default</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERSPECTIVE__DEFAULT = 1;

  /**
   * The feature id for the '<em><b>Display Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERSPECTIVE__DISPLAY_NAME = 2;

  /**
   * The feature id for the '<em><b>Languages</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERSPECTIVE__LANGUAGES = 3;

  /**
   * The feature id for the '<em><b>Actions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERSPECTIVE__ACTIONS = 4;

  /**
   * The feature id for the '<em><b>Mappings</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERSPECTIVE__MAPPINGS = 5;

  /**
   * The feature id for the '<em><b>Intralanguagemappings</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERSPECTIVE__INTRALANGUAGEMAPPINGS = 6;

  /**
   * The number of structural features of the '<em>Perspective</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERSPECTIVE_FEATURE_COUNT = 7;

  /**
   * The meta object id for the '{@link ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.impl.LanguageImpl <em>Language</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.impl.LanguageImpl
   * @see ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.impl.PerspectiveDSLPackageImpl#getLanguage()
   * @generated
   */
  int LANGUAGE = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LANGUAGE__NAME = 0;

  /**
   * The feature id for the '<em><b>Root Package</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LANGUAGE__ROOT_PACKAGE = 1;

  /**
   * The feature id for the '<em><b>Package Class Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LANGUAGE__PACKAGE_CLASS_NAME = 2;

  /**
   * The feature id for the '<em><b>Role Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LANGUAGE__ROLE_NAME = 3;

  /**
   * The number of structural features of the '<em>Language</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LANGUAGE_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.impl.LanguageElementMappingImpl <em>Language Element Mapping</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.impl.LanguageElementMappingImpl
   * @see ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.impl.PerspectiveDSLPackageImpl#getLanguageElementMapping()
   * @generated
   */
  int LANGUAGE_ELEMENT_MAPPING = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LANGUAGE_ELEMENT_MAPPING__NAME = 0;

  /**
   * The feature id for the '<em><b>From Cardinality</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LANGUAGE_ELEMENT_MAPPING__FROM_CARDINALITY = 1;

  /**
   * The feature id for the '<em><b>To Cardinality</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LANGUAGE_ELEMENT_MAPPING__TO_CARDINALITY = 2;

  /**
   * The feature id for the '<em><b>From Element</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LANGUAGE_ELEMENT_MAPPING__FROM_ELEMENT = 3;

  /**
   * The feature id for the '<em><b>From Role Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LANGUAGE_ELEMENT_MAPPING__FROM_ROLE_NAME = 4;

  /**
   * The feature id for the '<em><b>From Get Element</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LANGUAGE_ELEMENT_MAPPING__FROM_GET_ELEMENT = 5;

  /**
   * The feature id for the '<em><b>To Element</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LANGUAGE_ELEMENT_MAPPING__TO_ELEMENT = 6;

  /**
   * The feature id for the '<em><b>To Role Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LANGUAGE_ELEMENT_MAPPING__TO_ROLE_NAME = 7;

  /**
   * The feature id for the '<em><b>To Get Element</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LANGUAGE_ELEMENT_MAPPING__TO_GET_ELEMENT = 8;

  /**
   * The feature id for the '<em><b>Nested Mappings</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LANGUAGE_ELEMENT_MAPPING__NESTED_MAPPINGS = 9;

  /**
   * The feature id for the '<em><b>Inter Language Mapping Ends</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LANGUAGE_ELEMENT_MAPPING__INTER_LANGUAGE_MAPPING_ENDS = 10;

  /**
   * The number of structural features of the '<em>Language Element Mapping</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LANGUAGE_ELEMENT_MAPPING_FEATURE_COUNT = 11;

  /**
   * The meta object id for the '{@link ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.impl.NestedMappingImpl <em>Nested Mapping</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.impl.NestedMappingImpl
   * @see ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.impl.PerspectiveDSLPackageImpl#getNestedMapping()
   * @generated
   */
  int NESTED_MAPPING = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NESTED_MAPPING__NAME = 0;

  /**
   * The feature id for the '<em><b>From Element Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NESTED_MAPPING__FROM_ELEMENT_NAME = 1;

  /**
   * The feature id for the '<em><b>From Role Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NESTED_MAPPING__FROM_ROLE_NAME = 2;

  /**
   * The feature id for the '<em><b>To Element Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NESTED_MAPPING__TO_ELEMENT_NAME = 3;

  /**
   * The feature id for the '<em><b>To Role Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NESTED_MAPPING__TO_ROLE_NAME = 4;

  /**
   * The number of structural features of the '<em>Nested Mapping</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NESTED_MAPPING_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.impl.InterLanguageMappingEndImpl <em>Inter Language Mapping End</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.impl.InterLanguageMappingEndImpl
   * @see ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.impl.PerspectiveDSLPackageImpl#getInterLanguageMappingEnd()
   * @generated
   */
  int INTER_LANGUAGE_MAPPING_END = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INTER_LANGUAGE_MAPPING_END__NAME = 0;

  /**
   * The feature id for the '<em><b>Origin</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INTER_LANGUAGE_MAPPING_END__ORIGIN = 1;

  /**
   * The feature id for the '<em><b>Destination</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INTER_LANGUAGE_MAPPING_END__DESTINATION = 2;

  /**
   * The number of structural features of the '<em>Inter Language Mapping End</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INTER_LANGUAGE_MAPPING_END_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.impl.ActionImpl <em>Action</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.impl.ActionImpl
   * @see ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.impl.PerspectiveDSLPackageImpl#getAction()
   * @generated
   */
  int ACTION = 6;

  /**
   * The feature id for the '<em><b>Action Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION__ACTION_TYPE = 0;

  /**
   * The feature id for the '<em><b>Role Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION__ROLE_NAME = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION__NAME = 2;

  /**
   * The number of structural features of the '<em>Action</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.impl.IntraLanguageMappingImpl <em>Intra Language Mapping</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.impl.IntraLanguageMappingImpl
   * @see ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.impl.PerspectiveDSLPackageImpl#getIntraLanguageMapping()
   * @generated
   */
  int INTRA_LANGUAGE_MAPPING = 7;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INTRA_LANGUAGE_MAPPING__NAME = 0;

  /**
   * The feature id for the '<em><b>Closure</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INTRA_LANGUAGE_MAPPING__CLOSURE = 1;

  /**
   * The feature id for the '<em><b>Reuse</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INTRA_LANGUAGE_MAPPING__REUSE = 2;

  /**
   * The feature id for the '<em><b>Increase Depth</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INTRA_LANGUAGE_MAPPING__INCREASE_DEPTH = 3;

  /**
   * The feature id for the '<em><b>Change Model</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INTRA_LANGUAGE_MAPPING__CHANGE_MODEL = 4;

  /**
   * The feature id for the '<em><b>From Element</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INTRA_LANGUAGE_MAPPING__FROM_ELEMENT = 5;

  /**
   * The feature id for the '<em><b>From Get Element</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INTRA_LANGUAGE_MAPPING__FROM_GET_ELEMENT = 6;

  /**
   * The feature id for the '<em><b>Hops</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INTRA_LANGUAGE_MAPPING__HOPS = 7;

  /**
   * The number of structural features of the '<em>Intra Language Mapping</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INTRA_LANGUAGE_MAPPING_FEATURE_COUNT = 8;

  /**
   * The meta object id for the '{@link ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.impl.HopImpl <em>Hop</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.impl.HopImpl
   * @see ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.impl.PerspectiveDSLPackageImpl#getHop()
   * @generated
   */
  int HOP = 8;

  /**
   * The feature id for the '<em><b>Hop Element</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HOP__HOP_ELEMENT = 0;

  /**
   * The feature id for the '<em><b>From Get Hop</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HOP__FROM_GET_HOP = 1;

  /**
   * The number of structural features of the '<em>Hop</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HOP_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.Cardinality <em>Cardinality</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.Cardinality
   * @see ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.impl.PerspectiveDSLPackageImpl#getCardinality()
   * @generated
   */
  int CARDINALITY = 9;

  /**
   * The meta object id for the '{@link ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.PerspectiveActionType <em>Perspective Action Type</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.PerspectiveActionType
   * @see ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.impl.PerspectiveDSLPackageImpl#getPerspectiveActionType()
   * @generated
   */
  int PERSPECTIVE_ACTION_TYPE = 10;


  /**
   * Returns the meta object for class '{@link ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.PerspectiveModel <em>Perspective Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Perspective Model</em>'.
   * @see ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.PerspectiveModel
   * @generated
   */
  EClass getPerspectiveModel();

  /**
   * Returns the meta object for the containment reference list '{@link ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.PerspectiveModel#getPerspective <em>Perspective</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Perspective</em>'.
   * @see ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.PerspectiveModel#getPerspective()
   * @see #getPerspectiveModel()
   * @generated
   */
  EReference getPerspectiveModel_Perspective();

  /**
   * Returns the meta object for class '{@link ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.Perspective <em>Perspective</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Perspective</em>'.
   * @see ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.Perspective
   * @generated
   */
  EClass getPerspective();

  /**
   * Returns the meta object for the attribute '{@link ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.Perspective#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.Perspective#getName()
   * @see #getPerspective()
   * @generated
   */
  EAttribute getPerspective_Name();

  /**
   * Returns the meta object for the attribute '{@link ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.Perspective#getDefault <em>Default</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Default</em>'.
   * @see ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.Perspective#getDefault()
   * @see #getPerspective()
   * @generated
   */
  EAttribute getPerspective_Default();

  /**
   * Returns the meta object for the attribute '{@link ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.Perspective#getDisplayName <em>Display Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Display Name</em>'.
   * @see ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.Perspective#getDisplayName()
   * @see #getPerspective()
   * @generated
   */
  EAttribute getPerspective_DisplayName();

  /**
   * Returns the meta object for the containment reference list '{@link ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.Perspective#getLanguages <em>Languages</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Languages</em>'.
   * @see ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.Perspective#getLanguages()
   * @see #getPerspective()
   * @generated
   */
  EReference getPerspective_Languages();

  /**
   * Returns the meta object for the containment reference list '{@link ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.Perspective#getActions <em>Actions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Actions</em>'.
   * @see ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.Perspective#getActions()
   * @see #getPerspective()
   * @generated
   */
  EReference getPerspective_Actions();

  /**
   * Returns the meta object for the containment reference list '{@link ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.Perspective#getMappings <em>Mappings</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Mappings</em>'.
   * @see ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.Perspective#getMappings()
   * @see #getPerspective()
   * @generated
   */
  EReference getPerspective_Mappings();

  /**
   * Returns the meta object for the containment reference list '{@link ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.Perspective#getIntralanguagemappings <em>Intralanguagemappings</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Intralanguagemappings</em>'.
   * @see ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.Perspective#getIntralanguagemappings()
   * @see #getPerspective()
   * @generated
   */
  EReference getPerspective_Intralanguagemappings();

  /**
   * Returns the meta object for class '{@link ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.Language <em>Language</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Language</em>'.
   * @see ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.Language
   * @generated
   */
  EClass getLanguage();

  /**
   * Returns the meta object for the attribute '{@link ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.Language#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.Language#getName()
   * @see #getLanguage()
   * @generated
   */
  EAttribute getLanguage_Name();

  /**
   * Returns the meta object for the attribute '{@link ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.Language#getRootPackage <em>Root Package</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Root Package</em>'.
   * @see ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.Language#getRootPackage()
   * @see #getLanguage()
   * @generated
   */
  EAttribute getLanguage_RootPackage();

  /**
   * Returns the meta object for the attribute '{@link ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.Language#getPackageClassName <em>Package Class Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Package Class Name</em>'.
   * @see ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.Language#getPackageClassName()
   * @see #getLanguage()
   * @generated
   */
  EAttribute getLanguage_PackageClassName();

  /**
   * Returns the meta object for the attribute '{@link ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.Language#getRoleName <em>Role Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Role Name</em>'.
   * @see ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.Language#getRoleName()
   * @see #getLanguage()
   * @generated
   */
  EAttribute getLanguage_RoleName();

  /**
   * Returns the meta object for class '{@link ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.LanguageElementMapping <em>Language Element Mapping</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Language Element Mapping</em>'.
   * @see ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.LanguageElementMapping
   * @generated
   */
  EClass getLanguageElementMapping();

  /**
   * Returns the meta object for the attribute '{@link ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.LanguageElementMapping#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.LanguageElementMapping#getName()
   * @see #getLanguageElementMapping()
   * @generated
   */
  EAttribute getLanguageElementMapping_Name();

  /**
   * Returns the meta object for the attribute '{@link ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.LanguageElementMapping#getFromCardinality <em>From Cardinality</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>From Cardinality</em>'.
   * @see ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.LanguageElementMapping#getFromCardinality()
   * @see #getLanguageElementMapping()
   * @generated
   */
  EAttribute getLanguageElementMapping_FromCardinality();

  /**
   * Returns the meta object for the attribute '{@link ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.LanguageElementMapping#getToCardinality <em>To Cardinality</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>To Cardinality</em>'.
   * @see ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.LanguageElementMapping#getToCardinality()
   * @see #getLanguageElementMapping()
   * @generated
   */
  EAttribute getLanguageElementMapping_ToCardinality();

  /**
   * Returns the meta object for the attribute '{@link ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.LanguageElementMapping#getFromElement <em>From Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>From Element</em>'.
   * @see ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.LanguageElementMapping#getFromElement()
   * @see #getLanguageElementMapping()
   * @generated
   */
  EAttribute getLanguageElementMapping_FromElement();

  /**
   * Returns the meta object for the attribute '{@link ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.LanguageElementMapping#getFromRoleName <em>From Role Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>From Role Name</em>'.
   * @see ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.LanguageElementMapping#getFromRoleName()
   * @see #getLanguageElementMapping()
   * @generated
   */
  EAttribute getLanguageElementMapping_FromRoleName();

  /**
   * Returns the meta object for the attribute '{@link ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.LanguageElementMapping#getFromGetElement <em>From Get Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>From Get Element</em>'.
   * @see ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.LanguageElementMapping#getFromGetElement()
   * @see #getLanguageElementMapping()
   * @generated
   */
  EAttribute getLanguageElementMapping_FromGetElement();

  /**
   * Returns the meta object for the attribute '{@link ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.LanguageElementMapping#getToElement <em>To Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>To Element</em>'.
   * @see ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.LanguageElementMapping#getToElement()
   * @see #getLanguageElementMapping()
   * @generated
   */
  EAttribute getLanguageElementMapping_ToElement();

  /**
   * Returns the meta object for the attribute '{@link ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.LanguageElementMapping#getToRoleName <em>To Role Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>To Role Name</em>'.
   * @see ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.LanguageElementMapping#getToRoleName()
   * @see #getLanguageElementMapping()
   * @generated
   */
  EAttribute getLanguageElementMapping_ToRoleName();

  /**
   * Returns the meta object for the attribute '{@link ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.LanguageElementMapping#getToGetElement <em>To Get Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>To Get Element</em>'.
   * @see ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.LanguageElementMapping#getToGetElement()
   * @see #getLanguageElementMapping()
   * @generated
   */
  EAttribute getLanguageElementMapping_ToGetElement();

  /**
   * Returns the meta object for the containment reference list '{@link ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.LanguageElementMapping#getNestedMappings <em>Nested Mappings</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Nested Mappings</em>'.
   * @see ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.LanguageElementMapping#getNestedMappings()
   * @see #getLanguageElementMapping()
   * @generated
   */
  EReference getLanguageElementMapping_NestedMappings();

  /**
   * Returns the meta object for the containment reference list '{@link ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.LanguageElementMapping#getInterLanguageMappingEnds <em>Inter Language Mapping Ends</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Inter Language Mapping Ends</em>'.
   * @see ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.LanguageElementMapping#getInterLanguageMappingEnds()
   * @see #getLanguageElementMapping()
   * @generated
   */
  EReference getLanguageElementMapping_InterLanguageMappingEnds();

  /**
   * Returns the meta object for class '{@link ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.NestedMapping <em>Nested Mapping</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Nested Mapping</em>'.
   * @see ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.NestedMapping
   * @generated
   */
  EClass getNestedMapping();

  /**
   * Returns the meta object for the attribute '{@link ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.NestedMapping#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.NestedMapping#getName()
   * @see #getNestedMapping()
   * @generated
   */
  EAttribute getNestedMapping_Name();

  /**
   * Returns the meta object for the attribute '{@link ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.NestedMapping#getFromElementName <em>From Element Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>From Element Name</em>'.
   * @see ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.NestedMapping#getFromElementName()
   * @see #getNestedMapping()
   * @generated
   */
  EAttribute getNestedMapping_FromElementName();

  /**
   * Returns the meta object for the attribute '{@link ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.NestedMapping#getFromRoleName <em>From Role Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>From Role Name</em>'.
   * @see ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.NestedMapping#getFromRoleName()
   * @see #getNestedMapping()
   * @generated
   */
  EAttribute getNestedMapping_FromRoleName();

  /**
   * Returns the meta object for the attribute '{@link ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.NestedMapping#getToElementName <em>To Element Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>To Element Name</em>'.
   * @see ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.NestedMapping#getToElementName()
   * @see #getNestedMapping()
   * @generated
   */
  EAttribute getNestedMapping_ToElementName();

  /**
   * Returns the meta object for the attribute '{@link ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.NestedMapping#getToRoleName <em>To Role Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>To Role Name</em>'.
   * @see ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.NestedMapping#getToRoleName()
   * @see #getNestedMapping()
   * @generated
   */
  EAttribute getNestedMapping_ToRoleName();

  /**
   * Returns the meta object for class '{@link ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.InterLanguageMappingEnd <em>Inter Language Mapping End</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Inter Language Mapping End</em>'.
   * @see ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.InterLanguageMappingEnd
   * @generated
   */
  EClass getInterLanguageMappingEnd();

  /**
   * Returns the meta object for the attribute '{@link ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.InterLanguageMappingEnd#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.InterLanguageMappingEnd#getName()
   * @see #getInterLanguageMappingEnd()
   * @generated
   */
  EAttribute getInterLanguageMappingEnd_Name();

  /**
   * Returns the meta object for the attribute '{@link ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.InterLanguageMappingEnd#isOrigin <em>Origin</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Origin</em>'.
   * @see ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.InterLanguageMappingEnd#isOrigin()
   * @see #getInterLanguageMappingEnd()
   * @generated
   */
  EAttribute getInterLanguageMappingEnd_Origin();

  /**
   * Returns the meta object for the attribute '{@link ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.InterLanguageMappingEnd#isDestination <em>Destination</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Destination</em>'.
   * @see ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.InterLanguageMappingEnd#isDestination()
   * @see #getInterLanguageMappingEnd()
   * @generated
   */
  EAttribute getInterLanguageMappingEnd_Destination();

  /**
   * Returns the meta object for class '{@link ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.Action <em>Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Action</em>'.
   * @see ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.Action
   * @generated
   */
  EClass getAction();

  /**
   * Returns the meta object for the attribute '{@link ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.Action#getActionType <em>Action Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Action Type</em>'.
   * @see ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.Action#getActionType()
   * @see #getAction()
   * @generated
   */
  EAttribute getAction_ActionType();

  /**
   * Returns the meta object for the attribute '{@link ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.Action#getRoleName <em>Role Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Role Name</em>'.
   * @see ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.Action#getRoleName()
   * @see #getAction()
   * @generated
   */
  EAttribute getAction_RoleName();

  /**
   * Returns the meta object for the attribute '{@link ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.Action#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.Action#getName()
   * @see #getAction()
   * @generated
   */
  EAttribute getAction_Name();

  /**
   * Returns the meta object for class '{@link ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.IntraLanguageMapping <em>Intra Language Mapping</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Intra Language Mapping</em>'.
   * @see ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.IntraLanguageMapping
   * @generated
   */
  EClass getIntraLanguageMapping();

  /**
   * Returns the meta object for the attribute '{@link ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.IntraLanguageMapping#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.IntraLanguageMapping#getName()
   * @see #getIntraLanguageMapping()
   * @generated
   */
  EAttribute getIntraLanguageMapping_Name();

  /**
   * Returns the meta object for the attribute '{@link ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.IntraLanguageMapping#isClosure <em>Closure</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Closure</em>'.
   * @see ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.IntraLanguageMapping#isClosure()
   * @see #getIntraLanguageMapping()
   * @generated
   */
  EAttribute getIntraLanguageMapping_Closure();

  /**
   * Returns the meta object for the attribute '{@link ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.IntraLanguageMapping#isReuse <em>Reuse</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Reuse</em>'.
   * @see ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.IntraLanguageMapping#isReuse()
   * @see #getIntraLanguageMapping()
   * @generated
   */
  EAttribute getIntraLanguageMapping_Reuse();

  /**
   * Returns the meta object for the attribute '{@link ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.IntraLanguageMapping#isIncreaseDepth <em>Increase Depth</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Increase Depth</em>'.
   * @see ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.IntraLanguageMapping#isIncreaseDepth()
   * @see #getIntraLanguageMapping()
   * @generated
   */
  EAttribute getIntraLanguageMapping_IncreaseDepth();

  /**
   * Returns the meta object for the attribute '{@link ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.IntraLanguageMapping#isChangeModel <em>Change Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Change Model</em>'.
   * @see ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.IntraLanguageMapping#isChangeModel()
   * @see #getIntraLanguageMapping()
   * @generated
   */
  EAttribute getIntraLanguageMapping_ChangeModel();

  /**
   * Returns the meta object for the attribute '{@link ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.IntraLanguageMapping#getFromElement <em>From Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>From Element</em>'.
   * @see ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.IntraLanguageMapping#getFromElement()
   * @see #getIntraLanguageMapping()
   * @generated
   */
  EAttribute getIntraLanguageMapping_FromElement();

  /**
   * Returns the meta object for the attribute '{@link ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.IntraLanguageMapping#getFromGetElement <em>From Get Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>From Get Element</em>'.
   * @see ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.IntraLanguageMapping#getFromGetElement()
   * @see #getIntraLanguageMapping()
   * @generated
   */
  EAttribute getIntraLanguageMapping_FromGetElement();

  /**
   * Returns the meta object for the containment reference list '{@link ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.IntraLanguageMapping#getHops <em>Hops</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Hops</em>'.
   * @see ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.IntraLanguageMapping#getHops()
   * @see #getIntraLanguageMapping()
   * @generated
   */
  EReference getIntraLanguageMapping_Hops();

  /**
   * Returns the meta object for class '{@link ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.Hop <em>Hop</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Hop</em>'.
   * @see ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.Hop
   * @generated
   */
  EClass getHop();

  /**
   * Returns the meta object for the attribute '{@link ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.Hop#getHopElement <em>Hop Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Hop Element</em>'.
   * @see ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.Hop#getHopElement()
   * @see #getHop()
   * @generated
   */
  EAttribute getHop_HopElement();

  /**
   * Returns the meta object for the attribute '{@link ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.Hop#getFromGetHop <em>From Get Hop</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>From Get Hop</em>'.
   * @see ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.Hop#getFromGetHop()
   * @see #getHop()
   * @generated
   */
  EAttribute getHop_FromGetHop();

  /**
   * Returns the meta object for enum '{@link ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.Cardinality <em>Cardinality</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Cardinality</em>'.
   * @see ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.Cardinality
   * @generated
   */
  EEnum getCardinality();

  /**
   * Returns the meta object for enum '{@link ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.PerspectiveActionType <em>Perspective Action Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Perspective Action Type</em>'.
   * @see ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.PerspectiveActionType
   * @generated
   */
  EEnum getPerspectiveActionType();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  PerspectiveDSLFactory getPerspectiveDSLFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.impl.PerspectiveModelImpl <em>Perspective Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.impl.PerspectiveModelImpl
     * @see ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.impl.PerspectiveDSLPackageImpl#getPerspectiveModel()
     * @generated
     */
    EClass PERSPECTIVE_MODEL = eINSTANCE.getPerspectiveModel();

    /**
     * The meta object literal for the '<em><b>Perspective</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PERSPECTIVE_MODEL__PERSPECTIVE = eINSTANCE.getPerspectiveModel_Perspective();

    /**
     * The meta object literal for the '{@link ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.impl.PerspectiveImpl <em>Perspective</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.impl.PerspectiveImpl
     * @see ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.impl.PerspectiveDSLPackageImpl#getPerspective()
     * @generated
     */
    EClass PERSPECTIVE = eINSTANCE.getPerspective();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PERSPECTIVE__NAME = eINSTANCE.getPerspective_Name();

    /**
     * The meta object literal for the '<em><b>Default</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PERSPECTIVE__DEFAULT = eINSTANCE.getPerspective_Default();

    /**
     * The meta object literal for the '<em><b>Display Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PERSPECTIVE__DISPLAY_NAME = eINSTANCE.getPerspective_DisplayName();

    /**
     * The meta object literal for the '<em><b>Languages</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PERSPECTIVE__LANGUAGES = eINSTANCE.getPerspective_Languages();

    /**
     * The meta object literal for the '<em><b>Actions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PERSPECTIVE__ACTIONS = eINSTANCE.getPerspective_Actions();

    /**
     * The meta object literal for the '<em><b>Mappings</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PERSPECTIVE__MAPPINGS = eINSTANCE.getPerspective_Mappings();

    /**
     * The meta object literal for the '<em><b>Intralanguagemappings</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PERSPECTIVE__INTRALANGUAGEMAPPINGS = eINSTANCE.getPerspective_Intralanguagemappings();

    /**
     * The meta object literal for the '{@link ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.impl.LanguageImpl <em>Language</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.impl.LanguageImpl
     * @see ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.impl.PerspectiveDSLPackageImpl#getLanguage()
     * @generated
     */
    EClass LANGUAGE = eINSTANCE.getLanguage();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LANGUAGE__NAME = eINSTANCE.getLanguage_Name();

    /**
     * The meta object literal for the '<em><b>Root Package</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LANGUAGE__ROOT_PACKAGE = eINSTANCE.getLanguage_RootPackage();

    /**
     * The meta object literal for the '<em><b>Package Class Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LANGUAGE__PACKAGE_CLASS_NAME = eINSTANCE.getLanguage_PackageClassName();

    /**
     * The meta object literal for the '<em><b>Role Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LANGUAGE__ROLE_NAME = eINSTANCE.getLanguage_RoleName();

    /**
     * The meta object literal for the '{@link ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.impl.LanguageElementMappingImpl <em>Language Element Mapping</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.impl.LanguageElementMappingImpl
     * @see ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.impl.PerspectiveDSLPackageImpl#getLanguageElementMapping()
     * @generated
     */
    EClass LANGUAGE_ELEMENT_MAPPING = eINSTANCE.getLanguageElementMapping();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LANGUAGE_ELEMENT_MAPPING__NAME = eINSTANCE.getLanguageElementMapping_Name();

    /**
     * The meta object literal for the '<em><b>From Cardinality</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LANGUAGE_ELEMENT_MAPPING__FROM_CARDINALITY = eINSTANCE.getLanguageElementMapping_FromCardinality();

    /**
     * The meta object literal for the '<em><b>To Cardinality</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LANGUAGE_ELEMENT_MAPPING__TO_CARDINALITY = eINSTANCE.getLanguageElementMapping_ToCardinality();

    /**
     * The meta object literal for the '<em><b>From Element</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LANGUAGE_ELEMENT_MAPPING__FROM_ELEMENT = eINSTANCE.getLanguageElementMapping_FromElement();

    /**
     * The meta object literal for the '<em><b>From Role Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LANGUAGE_ELEMENT_MAPPING__FROM_ROLE_NAME = eINSTANCE.getLanguageElementMapping_FromRoleName();

    /**
     * The meta object literal for the '<em><b>From Get Element</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LANGUAGE_ELEMENT_MAPPING__FROM_GET_ELEMENT = eINSTANCE.getLanguageElementMapping_FromGetElement();

    /**
     * The meta object literal for the '<em><b>To Element</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LANGUAGE_ELEMENT_MAPPING__TO_ELEMENT = eINSTANCE.getLanguageElementMapping_ToElement();

    /**
     * The meta object literal for the '<em><b>To Role Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LANGUAGE_ELEMENT_MAPPING__TO_ROLE_NAME = eINSTANCE.getLanguageElementMapping_ToRoleName();

    /**
     * The meta object literal for the '<em><b>To Get Element</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LANGUAGE_ELEMENT_MAPPING__TO_GET_ELEMENT = eINSTANCE.getLanguageElementMapping_ToGetElement();

    /**
     * The meta object literal for the '<em><b>Nested Mappings</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LANGUAGE_ELEMENT_MAPPING__NESTED_MAPPINGS = eINSTANCE.getLanguageElementMapping_NestedMappings();

    /**
     * The meta object literal for the '<em><b>Inter Language Mapping Ends</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LANGUAGE_ELEMENT_MAPPING__INTER_LANGUAGE_MAPPING_ENDS = eINSTANCE.getLanguageElementMapping_InterLanguageMappingEnds();

    /**
     * The meta object literal for the '{@link ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.impl.NestedMappingImpl <em>Nested Mapping</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.impl.NestedMappingImpl
     * @see ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.impl.PerspectiveDSLPackageImpl#getNestedMapping()
     * @generated
     */
    EClass NESTED_MAPPING = eINSTANCE.getNestedMapping();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NESTED_MAPPING__NAME = eINSTANCE.getNestedMapping_Name();

    /**
     * The meta object literal for the '<em><b>From Element Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NESTED_MAPPING__FROM_ELEMENT_NAME = eINSTANCE.getNestedMapping_FromElementName();

    /**
     * The meta object literal for the '<em><b>From Role Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NESTED_MAPPING__FROM_ROLE_NAME = eINSTANCE.getNestedMapping_FromRoleName();

    /**
     * The meta object literal for the '<em><b>To Element Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NESTED_MAPPING__TO_ELEMENT_NAME = eINSTANCE.getNestedMapping_ToElementName();

    /**
     * The meta object literal for the '<em><b>To Role Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NESTED_MAPPING__TO_ROLE_NAME = eINSTANCE.getNestedMapping_ToRoleName();

    /**
     * The meta object literal for the '{@link ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.impl.InterLanguageMappingEndImpl <em>Inter Language Mapping End</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.impl.InterLanguageMappingEndImpl
     * @see ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.impl.PerspectiveDSLPackageImpl#getInterLanguageMappingEnd()
     * @generated
     */
    EClass INTER_LANGUAGE_MAPPING_END = eINSTANCE.getInterLanguageMappingEnd();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INTER_LANGUAGE_MAPPING_END__NAME = eINSTANCE.getInterLanguageMappingEnd_Name();

    /**
     * The meta object literal for the '<em><b>Origin</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INTER_LANGUAGE_MAPPING_END__ORIGIN = eINSTANCE.getInterLanguageMappingEnd_Origin();

    /**
     * The meta object literal for the '<em><b>Destination</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INTER_LANGUAGE_MAPPING_END__DESTINATION = eINSTANCE.getInterLanguageMappingEnd_Destination();

    /**
     * The meta object literal for the '{@link ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.impl.ActionImpl <em>Action</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.impl.ActionImpl
     * @see ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.impl.PerspectiveDSLPackageImpl#getAction()
     * @generated
     */
    EClass ACTION = eINSTANCE.getAction();

    /**
     * The meta object literal for the '<em><b>Action Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ACTION__ACTION_TYPE = eINSTANCE.getAction_ActionType();

    /**
     * The meta object literal for the '<em><b>Role Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ACTION__ROLE_NAME = eINSTANCE.getAction_RoleName();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ACTION__NAME = eINSTANCE.getAction_Name();

    /**
     * The meta object literal for the '{@link ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.impl.IntraLanguageMappingImpl <em>Intra Language Mapping</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.impl.IntraLanguageMappingImpl
     * @see ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.impl.PerspectiveDSLPackageImpl#getIntraLanguageMapping()
     * @generated
     */
    EClass INTRA_LANGUAGE_MAPPING = eINSTANCE.getIntraLanguageMapping();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INTRA_LANGUAGE_MAPPING__NAME = eINSTANCE.getIntraLanguageMapping_Name();

    /**
     * The meta object literal for the '<em><b>Closure</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INTRA_LANGUAGE_MAPPING__CLOSURE = eINSTANCE.getIntraLanguageMapping_Closure();

    /**
     * The meta object literal for the '<em><b>Reuse</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INTRA_LANGUAGE_MAPPING__REUSE = eINSTANCE.getIntraLanguageMapping_Reuse();

    /**
     * The meta object literal for the '<em><b>Increase Depth</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INTRA_LANGUAGE_MAPPING__INCREASE_DEPTH = eINSTANCE.getIntraLanguageMapping_IncreaseDepth();

    /**
     * The meta object literal for the '<em><b>Change Model</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INTRA_LANGUAGE_MAPPING__CHANGE_MODEL = eINSTANCE.getIntraLanguageMapping_ChangeModel();

    /**
     * The meta object literal for the '<em><b>From Element</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INTRA_LANGUAGE_MAPPING__FROM_ELEMENT = eINSTANCE.getIntraLanguageMapping_FromElement();

    /**
     * The meta object literal for the '<em><b>From Get Element</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INTRA_LANGUAGE_MAPPING__FROM_GET_ELEMENT = eINSTANCE.getIntraLanguageMapping_FromGetElement();

    /**
     * The meta object literal for the '<em><b>Hops</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INTRA_LANGUAGE_MAPPING__HOPS = eINSTANCE.getIntraLanguageMapping_Hops();

    /**
     * The meta object literal for the '{@link ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.impl.HopImpl <em>Hop</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.impl.HopImpl
     * @see ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.impl.PerspectiveDSLPackageImpl#getHop()
     * @generated
     */
    EClass HOP = eINSTANCE.getHop();

    /**
     * The meta object literal for the '<em><b>Hop Element</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute HOP__HOP_ELEMENT = eINSTANCE.getHop_HopElement();

    /**
     * The meta object literal for the '<em><b>From Get Hop</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute HOP__FROM_GET_HOP = eINSTANCE.getHop_FromGetHop();

    /**
     * The meta object literal for the '{@link ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.Cardinality <em>Cardinality</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.Cardinality
     * @see ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.impl.PerspectiveDSLPackageImpl#getCardinality()
     * @generated
     */
    EEnum CARDINALITY = eINSTANCE.getCardinality();

    /**
     * The meta object literal for the '{@link ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.PerspectiveActionType <em>Perspective Action Type</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.PerspectiveActionType
     * @see ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.impl.PerspectiveDSLPackageImpl#getPerspectiveActionType()
     * @generated
     */
    EEnum PERSPECTIVE_ACTION_TYPE = eINSTANCE.getPerspectiveActionType();

  }

} //PerspectiveDSLPackage
