/**
 * generated by Xtext 2.22.0
 */
package ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.PerspectiveDSLPackage
 * @generated
 */
public interface PerspectiveDSLFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  PerspectiveDSLFactory eINSTANCE = ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.impl.PerspectiveDSLFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Perspective Model</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Perspective Model</em>'.
   * @generated
   */
  PerspectiveModel createPerspectiveModel();

  /**
   * Returns a new object of class '<em>Perspective</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Perspective</em>'.
   * @generated
   */
  Perspective createPerspective();

  /**
   * Returns a new object of class '<em>Language</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Language</em>'.
   * @generated
   */
  Language createLanguage();

  /**
   * Returns a new object of class '<em>Language Element Mapping</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Language Element Mapping</em>'.
   * @generated
   */
  LanguageElementMapping createLanguageElementMapping();

  /**
   * Returns a new object of class '<em>Nested Mapping</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Nested Mapping</em>'.
   * @generated
   */
  NestedMapping createNestedMapping();

  /**
   * Returns a new object of class '<em>Inter Language Mapping End</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Inter Language Mapping End</em>'.
   * @generated
   */
  InterLanguageMappingEnd createInterLanguageMappingEnd();

  /**
   * Returns a new object of class '<em>Action</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Action</em>'.
   * @generated
   */
  Action createAction();

  /**
   * Returns a new object of class '<em>Intra Language Mapping</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Intra Language Mapping</em>'.
   * @generated
   */
  IntraLanguageMapping createIntraLanguageMapping();

  /**
   * Returns a new object of class '<em>Hop</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Hop</em>'.
   * @generated
   */
  Hop createHop();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  PerspectiveDSLPackage getPerspectiveDSLPackage();

} //PerspectiveDSLFactory
