/**
 * generated by Xtext 2.22.0
 */
package ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Perspective Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.PerspectiveModel#getPerspective <em>Perspective</em>}</li>
 * </ul>
 *
 * @see ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.PerspectiveDSLPackage#getPerspectiveModel()
 * @model
 * @generated
 */
public interface PerspectiveModel extends EObject
{
  /**
   * Returns the value of the '<em><b>Perspective</b></em>' containment reference list.
   * The list contents are of type {@link ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.Perspective}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Perspective</em>' containment reference list.
   * @see ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.PerspectiveDSLPackage#getPerspectiveModel_Perspective()
   * @model containment="true"
   * @generated
   */
  EList<Perspective> getPerspective();

} // PerspectiveModel
