/*
 * generated by Xtext 2.22.0
 */
package ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.parser.antlr;

import ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.parser.antlr.internal.InternalPerspectiveDSLParser;
import ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.services.PerspectiveDSLGrammarAccess;
import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class PerspectiveDSLParser extends AbstractAntlrParser {

	@Inject
	private PerspectiveDSLGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalPerspectiveDSLParser createParser(XtextTokenStream stream) {
		return new InternalPerspectiveDSLParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "PerspectiveModel";
	}

	public PerspectiveDSLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(PerspectiveDSLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
