/*
 * generated by Xtext 2.22.0
 */
package ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.ui;

import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.xtext.perspectivedsl.ui.internal.PerspectivedslActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class PerspectiveDSLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(PerspectivedslActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		PerspectivedslActivator activator = PerspectivedslActivator.getInstance();
		return activator != null ? activator.getInjector(PerspectivedslActivator.CA_MCGILL_SEL_PERSPECTIVEDSL_CA_MCGILL_SEL_PERSPECTIVEDSL) : null;
	}

}
