/*
 * generated by Xtext 2.22.0
 */
package ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.serializer;

import ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.services.PerspectiveDSLGrammarAccess;
import com.google.inject.Inject;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.GroupAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;

@SuppressWarnings("all")
public class PerspectiveDSLSyntacticSequencer extends AbstractSyntacticSequencer {

	protected PerspectiveDSLGrammarAccess grammarAccess;
	protected AbstractElementAlias match_LanguageElementMapping___InterLanguageMappingEndsKeyword_28_0_ColonKeyword_28_1_EndKeyword_28_3__q;
	protected AbstractElementAlias match_LanguageElementMapping___NestedKeyword_27_0_MappingsKeyword_27_1_ColonKeyword_27_2_EndKeyword_27_4__q;
	protected AbstractElementAlias match_Perspective___IntraLanguageMappingsKeyword_20_0_ColonKeyword_20_1__q;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (PerspectiveDSLGrammarAccess) access;
		match_LanguageElementMapping___InterLanguageMappingEndsKeyword_28_0_ColonKeyword_28_1_EndKeyword_28_3__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getLanguageElementMappingAccess().getInterLanguageMappingEndsKeyword_28_0()), new TokenAlias(false, false, grammarAccess.getLanguageElementMappingAccess().getColonKeyword_28_1()), new TokenAlias(false, false, grammarAccess.getLanguageElementMappingAccess().getEndKeyword_28_3()));
		match_LanguageElementMapping___NestedKeyword_27_0_MappingsKeyword_27_1_ColonKeyword_27_2_EndKeyword_27_4__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getLanguageElementMappingAccess().getNestedKeyword_27_0()), new TokenAlias(false, false, grammarAccess.getLanguageElementMappingAccess().getMappingsKeyword_27_1()), new TokenAlias(false, false, grammarAccess.getLanguageElementMappingAccess().getColonKeyword_27_2()), new TokenAlias(false, false, grammarAccess.getLanguageElementMappingAccess().getEndKeyword_27_4()));
		match_Perspective___IntraLanguageMappingsKeyword_20_0_ColonKeyword_20_1__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getPerspectiveAccess().getIntraLanguageMappingsKeyword_20_0()), new TokenAlias(false, false, grammarAccess.getPerspectiveAccess().getColonKeyword_20_1()));
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		return "";
	}
	
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if (match_LanguageElementMapping___InterLanguageMappingEndsKeyword_28_0_ColonKeyword_28_1_EndKeyword_28_3__q.equals(syntax))
				emit_LanguageElementMapping___InterLanguageMappingEndsKeyword_28_0_ColonKeyword_28_1_EndKeyword_28_3__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_LanguageElementMapping___NestedKeyword_27_0_MappingsKeyword_27_1_ColonKeyword_27_2_EndKeyword_27_4__q.equals(syntax))
				emit_LanguageElementMapping___NestedKeyword_27_0_MappingsKeyword_27_1_ColonKeyword_27_2_EndKeyword_27_4__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Perspective___IntraLanguageMappingsKeyword_20_0_ColonKeyword_20_1__q.equals(syntax))
				emit_Perspective___IntraLanguageMappingsKeyword_20_0_ColonKeyword_20_1__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * Ambiguous syntax:
	 *     ('interLanguageMappingEnds' ':' 'end')?
	 *
	 * This ambiguous syntax occurs at:
	 *     nestedMappings+=NestedMapping 'end' (ambiguity) '}' (rule end)
	 *     toGetElement=STRING ';' ('nested' 'mappings' ':' 'end')? (ambiguity) '}' (rule end)
	 */
	protected void emit_LanguageElementMapping___InterLanguageMappingEndsKeyword_28_0_ColonKeyword_28_1_EndKeyword_28_3__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('nested' 'mappings' ':' 'end')?
	 *
	 * This ambiguous syntax occurs at:
	 *     toGetElement=STRING ';' (ambiguity) 'interLanguageMappingEnds' ':' interLanguageMappingEnds+=InterLanguageMappingEnd
	 *     toGetElement=STRING ';' (ambiguity) ('interLanguageMappingEnds' ':' 'end')? '}' (rule end)
	 */
	protected void emit_LanguageElementMapping___NestedKeyword_27_0_MappingsKeyword_27_1_ColonKeyword_27_2_EndKeyword_27_4__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('intraLanguageMappings' ':')?
	 *
	 * This ambiguous syntax occurs at:
	 *     actions+=Action 'end' 'mappings' ':' 'end' (ambiguity) 'end' '}' (rule end)
	 *     displayName=STRING ';' 'languages' ':' 'end' 'actions' ':' 'end' 'mappings' ':' 'end' (ambiguity) 'end' '}' (rule end)
	 *     languages+=Language 'end' 'actions' ':' 'end' 'mappings' ':' 'end' (ambiguity) 'end' '}' (rule end)
	 *     mappings+=LanguageElementMapping 'end' (ambiguity) 'end' '}' (rule end)
	 */
	protected void emit_Perspective___IntraLanguageMappingsKeyword_20_0_ColonKeyword_20_1__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
