/*
 * generated by Xtext 2.22.0
 */
package ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.EnumLiteralDeclaration;
import org.eclipse.xtext.EnumRule;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class PerspectiveDSLGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class PerspectiveModelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.PerspectiveDSL.PerspectiveModel");
		private final Assignment cPerspectiveAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cPerspectivePerspectiveParserRuleCall_0 = (RuleCall)cPerspectiveAssignment.eContents().get(0);
		
		//PerspectiveModel:
		//	perspective+=Perspective*;
		@Override public ParserRule getRule() { return rule; }
		
		//perspective+=Perspective*
		public Assignment getPerspectiveAssignment() { return cPerspectiveAssignment; }
		
		//Perspective
		public RuleCall getPerspectivePerspectiveParserRuleCall_0() { return cPerspectivePerspectiveParserRuleCall_0; }
	}
	public class PerspectiveElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.PerspectiveDSL.Perspective");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cPerspectiveKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cDefaultKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cDefaultAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cDefaultIDTerminalRuleCall_3_1_0 = (RuleCall)cDefaultAssignment_3_1.eContents().get(0);
		private final Keyword cSemicolonKeyword_3_2 = (Keyword)cGroup_3.eContents().get(2);
		private final Keyword cDisplayKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Keyword cNameKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cDisplayNameAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cDisplayNameSTRINGTerminalRuleCall_6_0 = (RuleCall)cDisplayNameAssignment_6.eContents().get(0);
		private final Keyword cSemicolonKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Keyword cLanguagesKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Keyword cColonKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Assignment cLanguagesAssignment_10 = (Assignment)cGroup.eContents().get(10);
		private final RuleCall cLanguagesLanguageParserRuleCall_10_0 = (RuleCall)cLanguagesAssignment_10.eContents().get(0);
		private final Keyword cEndKeyword_11 = (Keyword)cGroup.eContents().get(11);
		private final Keyword cActionsKeyword_12 = (Keyword)cGroup.eContents().get(12);
		private final Keyword cColonKeyword_13 = (Keyword)cGroup.eContents().get(13);
		private final Assignment cActionsAssignment_14 = (Assignment)cGroup.eContents().get(14);
		private final RuleCall cActionsActionParserRuleCall_14_0 = (RuleCall)cActionsAssignment_14.eContents().get(0);
		private final Keyword cEndKeyword_15 = (Keyword)cGroup.eContents().get(15);
		private final Keyword cMappingsKeyword_16 = (Keyword)cGroup.eContents().get(16);
		private final Keyword cColonKeyword_17 = (Keyword)cGroup.eContents().get(17);
		private final Assignment cMappingsAssignment_18 = (Assignment)cGroup.eContents().get(18);
		private final RuleCall cMappingsLanguageElementMappingParserRuleCall_18_0 = (RuleCall)cMappingsAssignment_18.eContents().get(0);
		private final Keyword cEndKeyword_19 = (Keyword)cGroup.eContents().get(19);
		private final Group cGroup_20 = (Group)cGroup.eContents().get(20);
		private final Keyword cIntraLanguageMappingsKeyword_20_0 = (Keyword)cGroup_20.eContents().get(0);
		private final Keyword cColonKeyword_20_1 = (Keyword)cGroup_20.eContents().get(1);
		private final Assignment cIntralanguagemappingsAssignment_20_2 = (Assignment)cGroup_20.eContents().get(2);
		private final RuleCall cIntralanguagemappingsIntraLanguageMappingParserRuleCall_20_2_0 = (RuleCall)cIntralanguagemappingsAssignment_20_2.eContents().get(0);
		private final Keyword cEndKeyword_21 = (Keyword)cGroup.eContents().get(21);
		private final Keyword cRightCurlyBracketKeyword_22 = (Keyword)cGroup.eContents().get(22);
		
		//Perspective:
		//	'perspective' name=ID '{' ('default' default=ID ';')?
		//	'display' 'name' displayName=STRING ';'
		//	'languages' ':'
		//	languages+=Language*
		//	'end'
		//	'actions' ':'
		//	actions+=Action*
		//	'end'
		//	'mappings' ':'
		//	mappings+=LanguageElementMapping*
		//	'end' ('intraLanguageMappings' ':'
		//	intralanguagemappings+=IntraLanguageMapping*)?
		//	'end'
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'perspective' name=ID '{' ('default' default=ID ';')? 'display' 'name' displayName=STRING ';' 'languages' ':'
		//languages+=Language* 'end' 'actions' ':' actions+=Action* 'end' 'mappings' ':' mappings+=LanguageElementMapping* 'end'
		//('intraLanguageMappings' ':' intralanguagemappings+=IntraLanguageMapping*)? 'end' '}'
		public Group getGroup() { return cGroup; }
		
		//'perspective'
		public Keyword getPerspectiveKeyword_0() { return cPerspectiveKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('default' default=ID ';')?
		public Group getGroup_3() { return cGroup_3; }
		
		//'default'
		public Keyword getDefaultKeyword_3_0() { return cDefaultKeyword_3_0; }
		
		//default=ID
		public Assignment getDefaultAssignment_3_1() { return cDefaultAssignment_3_1; }
		
		//ID
		public RuleCall getDefaultIDTerminalRuleCall_3_1_0() { return cDefaultIDTerminalRuleCall_3_1_0; }
		
		//';'
		public Keyword getSemicolonKeyword_3_2() { return cSemicolonKeyword_3_2; }
		
		//'display'
		public Keyword getDisplayKeyword_4() { return cDisplayKeyword_4; }
		
		//'name'
		public Keyword getNameKeyword_5() { return cNameKeyword_5; }
		
		//displayName=STRING
		public Assignment getDisplayNameAssignment_6() { return cDisplayNameAssignment_6; }
		
		//STRING
		public RuleCall getDisplayNameSTRINGTerminalRuleCall_6_0() { return cDisplayNameSTRINGTerminalRuleCall_6_0; }
		
		//';'
		public Keyword getSemicolonKeyword_7() { return cSemicolonKeyword_7; }
		
		//'languages'
		public Keyword getLanguagesKeyword_8() { return cLanguagesKeyword_8; }
		
		//':'
		public Keyword getColonKeyword_9() { return cColonKeyword_9; }
		
		//languages+=Language*
		public Assignment getLanguagesAssignment_10() { return cLanguagesAssignment_10; }
		
		//Language
		public RuleCall getLanguagesLanguageParserRuleCall_10_0() { return cLanguagesLanguageParserRuleCall_10_0; }
		
		//'end'
		public Keyword getEndKeyword_11() { return cEndKeyword_11; }
		
		//'actions'
		public Keyword getActionsKeyword_12() { return cActionsKeyword_12; }
		
		//':'
		public Keyword getColonKeyword_13() { return cColonKeyword_13; }
		
		//actions+=Action*
		public Assignment getActionsAssignment_14() { return cActionsAssignment_14; }
		
		//Action
		public RuleCall getActionsActionParserRuleCall_14_0() { return cActionsActionParserRuleCall_14_0; }
		
		//'end'
		public Keyword getEndKeyword_15() { return cEndKeyword_15; }
		
		//'mappings'
		public Keyword getMappingsKeyword_16() { return cMappingsKeyword_16; }
		
		//':'
		public Keyword getColonKeyword_17() { return cColonKeyword_17; }
		
		//mappings+=LanguageElementMapping*
		public Assignment getMappingsAssignment_18() { return cMappingsAssignment_18; }
		
		//LanguageElementMapping
		public RuleCall getMappingsLanguageElementMappingParserRuleCall_18_0() { return cMappingsLanguageElementMappingParserRuleCall_18_0; }
		
		//'end'
		public Keyword getEndKeyword_19() { return cEndKeyword_19; }
		
		//('intraLanguageMappings' ':' intralanguagemappings+=IntraLanguageMapping*)?
		public Group getGroup_20() { return cGroup_20; }
		
		//'intraLanguageMappings'
		public Keyword getIntraLanguageMappingsKeyword_20_0() { return cIntraLanguageMappingsKeyword_20_0; }
		
		//':'
		public Keyword getColonKeyword_20_1() { return cColonKeyword_20_1; }
		
		//intralanguagemappings+=IntraLanguageMapping*
		public Assignment getIntralanguagemappingsAssignment_20_2() { return cIntralanguagemappingsAssignment_20_2; }
		
		//IntraLanguageMapping
		public RuleCall getIntralanguagemappingsIntraLanguageMappingParserRuleCall_20_2_0() { return cIntralanguagemappingsIntraLanguageMappingParserRuleCall_20_2_0; }
		
		//'end'
		public Keyword getEndKeyword_21() { return cEndKeyword_21; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_22() { return cRightCurlyBracketKeyword_22; }
	}
	public class LanguageElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.PerspectiveDSL.Language");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cExistingKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLanguageKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameIDTerminalRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cRootPackageKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cRootPackageAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cRootPackageSTRINGTerminalRuleCall_5_0 = (RuleCall)cRootPackageAssignment_5.eContents().get(0);
		private final Keyword cSemicolonKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Keyword cPackageClassNameKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cPackageClassNameAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cPackageClassNameIDTerminalRuleCall_8_0 = (RuleCall)cPackageClassNameAssignment_8.eContents().get(0);
		private final Keyword cSemicolonKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Keyword cRoleNameKeyword_10 = (Keyword)cGroup.eContents().get(10);
		private final Assignment cRoleNameAssignment_11 = (Assignment)cGroup.eContents().get(11);
		private final RuleCall cRoleNameIDTerminalRuleCall_11_0 = (RuleCall)cRoleNameAssignment_11.eContents().get(0);
		private final Keyword cSemicolonKeyword_12 = (Keyword)cGroup.eContents().get(12);
		private final Keyword cRightCurlyBracketKeyword_13 = (Keyword)cGroup.eContents().get(13);
		
		//Language:
		//	'existing' 'language' name=ID '{'
		//	"rootPackage" rootPackage=STRING ';'
		//	"packageClassName" packageClassName=ID ';'
		//	"roleName" roleName=ID ';'
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'existing' 'language' name=ID '{' "rootPackage" rootPackage=STRING ';' "packageClassName" packageClassName=ID ';'
		//"roleName" roleName=ID ';' '}'
		public Group getGroup() { return cGroup; }
		
		//'existing'
		public Keyword getExistingKeyword_0() { return cExistingKeyword_0; }
		
		//'language'
		public Keyword getLanguageKeyword_1() { return cLanguageKeyword_1; }
		
		//name=ID
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_2_0() { return cNameIDTerminalRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//"rootPackage"
		public Keyword getRootPackageKeyword_4() { return cRootPackageKeyword_4; }
		
		//rootPackage=STRING
		public Assignment getRootPackageAssignment_5() { return cRootPackageAssignment_5; }
		
		//STRING
		public RuleCall getRootPackageSTRINGTerminalRuleCall_5_0() { return cRootPackageSTRINGTerminalRuleCall_5_0; }
		
		//';'
		public Keyword getSemicolonKeyword_6() { return cSemicolonKeyword_6; }
		
		//"packageClassName"
		public Keyword getPackageClassNameKeyword_7() { return cPackageClassNameKeyword_7; }
		
		//packageClassName=ID
		public Assignment getPackageClassNameAssignment_8() { return cPackageClassNameAssignment_8; }
		
		//ID
		public RuleCall getPackageClassNameIDTerminalRuleCall_8_0() { return cPackageClassNameIDTerminalRuleCall_8_0; }
		
		//';'
		public Keyword getSemicolonKeyword_9() { return cSemicolonKeyword_9; }
		
		//"roleName"
		public Keyword getRoleNameKeyword_10() { return cRoleNameKeyword_10; }
		
		//roleName=ID
		public Assignment getRoleNameAssignment_11() { return cRoleNameAssignment_11; }
		
		//ID
		public RuleCall getRoleNameIDTerminalRuleCall_11_0() { return cRoleNameIDTerminalRuleCall_11_0; }
		
		//';'
		public Keyword getSemicolonKeyword_12() { return cSemicolonKeyword_12; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_13() { return cRightCurlyBracketKeyword_13; }
	}
	public class LanguageElementMappingElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.PerspectiveDSL.LanguageElementMapping");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cMappingKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cFromCardinalityKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cColonKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cFromCardinalityAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cFromCardinalityCardinalityEnumRuleCall_5_0 = (RuleCall)cFromCardinalityAssignment_5.eContents().get(0);
		private final Keyword cSemicolonKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Keyword cToCardinalityKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Keyword cColonKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Assignment cToCardinalityAssignment_9 = (Assignment)cGroup.eContents().get(9);
		private final RuleCall cToCardinalityCardinalityEnumRuleCall_9_0 = (RuleCall)cToCardinalityAssignment_9.eContents().get(0);
		private final Keyword cSemicolonKeyword_10 = (Keyword)cGroup.eContents().get(10);
		private final Keyword cFromElementKeyword_11 = (Keyword)cGroup.eContents().get(11);
		private final Keyword cColonKeyword_12 = (Keyword)cGroup.eContents().get(12);
		private final Assignment cFromElementAssignment_13 = (Assignment)cGroup.eContents().get(13);
		private final RuleCall cFromElementIDTerminalRuleCall_13_0 = (RuleCall)cFromElementAssignment_13.eContents().get(0);
		private final Keyword cFromKeyword_14 = (Keyword)cGroup.eContents().get(14);
		private final Assignment cFromRoleNameAssignment_15 = (Assignment)cGroup.eContents().get(15);
		private final RuleCall cFromRoleNameIDTerminalRuleCall_15_0 = (RuleCall)cFromRoleNameAssignment_15.eContents().get(0);
		private final Keyword cFromGetElementKeyword_16 = (Keyword)cGroup.eContents().get(16);
		private final Assignment cFromGetElementAssignment_17 = (Assignment)cGroup.eContents().get(17);
		private final RuleCall cFromGetElementSTRINGTerminalRuleCall_17_0 = (RuleCall)cFromGetElementAssignment_17.eContents().get(0);
		private final Keyword cSemicolonKeyword_18 = (Keyword)cGroup.eContents().get(18);
		private final Keyword cToELementKeyword_19 = (Keyword)cGroup.eContents().get(19);
		private final Keyword cColonKeyword_20 = (Keyword)cGroup.eContents().get(20);
		private final Assignment cToElementAssignment_21 = (Assignment)cGroup.eContents().get(21);
		private final RuleCall cToElementIDTerminalRuleCall_21_0 = (RuleCall)cToElementAssignment_21.eContents().get(0);
		private final Keyword cFromKeyword_22 = (Keyword)cGroup.eContents().get(22);
		private final Assignment cToRoleNameAssignment_23 = (Assignment)cGroup.eContents().get(23);
		private final RuleCall cToRoleNameIDTerminalRuleCall_23_0 = (RuleCall)cToRoleNameAssignment_23.eContents().get(0);
		private final Keyword cToGetElementKeyword_24 = (Keyword)cGroup.eContents().get(24);
		private final Assignment cToGetElementAssignment_25 = (Assignment)cGroup.eContents().get(25);
		private final RuleCall cToGetElementSTRINGTerminalRuleCall_25_0 = (RuleCall)cToGetElementAssignment_25.eContents().get(0);
		private final Keyword cSemicolonKeyword_26 = (Keyword)cGroup.eContents().get(26);
		private final Group cGroup_27 = (Group)cGroup.eContents().get(27);
		private final Keyword cNestedKeyword_27_0 = (Keyword)cGroup_27.eContents().get(0);
		private final Keyword cMappingsKeyword_27_1 = (Keyword)cGroup_27.eContents().get(1);
		private final Keyword cColonKeyword_27_2 = (Keyword)cGroup_27.eContents().get(2);
		private final Assignment cNestedMappingsAssignment_27_3 = (Assignment)cGroup_27.eContents().get(3);
		private final RuleCall cNestedMappingsNestedMappingParserRuleCall_27_3_0 = (RuleCall)cNestedMappingsAssignment_27_3.eContents().get(0);
		private final Keyword cEndKeyword_27_4 = (Keyword)cGroup_27.eContents().get(4);
		private final Group cGroup_28 = (Group)cGroup.eContents().get(28);
		private final Keyword cInterLanguageMappingEndsKeyword_28_0 = (Keyword)cGroup_28.eContents().get(0);
		private final Keyword cColonKeyword_28_1 = (Keyword)cGroup_28.eContents().get(1);
		private final Assignment cInterLanguageMappingEndsAssignment_28_2 = (Assignment)cGroup_28.eContents().get(2);
		private final RuleCall cInterLanguageMappingEndsInterLanguageMappingEndParserRuleCall_28_2_0 = (RuleCall)cInterLanguageMappingEndsAssignment_28_2.eContents().get(0);
		private final Keyword cEndKeyword_28_3 = (Keyword)cGroup_28.eContents().get(3);
		private final Keyword cRightCurlyBracketKeyword_29 = (Keyword)cGroup.eContents().get(29);
		
		//LanguageElementMapping:
		//	'mapping' name=ID '{'
		//	//        'relationship' ':' relationship = Relationship';'
		//	'fromCardinality' ':' fromCardinality=Cardinality ';'
		//	'toCardinality' ':' toCardinality=Cardinality ';'
		//	'fromElement' ':' fromElement=ID 'from' fromRoleName=ID 'fromGetElement' fromGetElement=STRING ';'
		//	'toELement' ':' toElement=ID 'from' toRoleName=ID 'toGetElement' toGetElement=STRING ';' ('nested' 'mappings' ':'
		//	nestedMappings+=NestedMapping*
		//	'end')? ('interLanguageMappingEnds' ':'
		//	interLanguageMappingEnds+=InterLanguageMappingEnd*
		//	'end')?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'mapping' name=ID '{' //        'relationship' ':' relationship = Relationship';'
		//'fromCardinality' ':' fromCardinality=Cardinality ';' 'toCardinality' ':' toCardinality=Cardinality ';' 'fromElement'
		//':' fromElement=ID 'from' fromRoleName=ID 'fromGetElement' fromGetElement=STRING ';' 'toELement' ':' toElement=ID
		//'from' toRoleName=ID 'toGetElement' toGetElement=STRING ';' ('nested' 'mappings' ':' nestedMappings+=NestedMapping*
		//'end')? ('interLanguageMappingEnds' ':' interLanguageMappingEnds+=InterLanguageMappingEnd* 'end')? '}'
		public Group getGroup() { return cGroup; }
		
		//'mapping'
		public Keyword getMappingKeyword_0() { return cMappingKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		////        'relationship' ':' relationship = Relationship';'
		//'fromCardinality'
		public Keyword getFromCardinalityKeyword_3() { return cFromCardinalityKeyword_3; }
		
		//':'
		public Keyword getColonKeyword_4() { return cColonKeyword_4; }
		
		//fromCardinality=Cardinality
		public Assignment getFromCardinalityAssignment_5() { return cFromCardinalityAssignment_5; }
		
		//Cardinality
		public RuleCall getFromCardinalityCardinalityEnumRuleCall_5_0() { return cFromCardinalityCardinalityEnumRuleCall_5_0; }
		
		//';'
		public Keyword getSemicolonKeyword_6() { return cSemicolonKeyword_6; }
		
		//'toCardinality'
		public Keyword getToCardinalityKeyword_7() { return cToCardinalityKeyword_7; }
		
		//':'
		public Keyword getColonKeyword_8() { return cColonKeyword_8; }
		
		//toCardinality=Cardinality
		public Assignment getToCardinalityAssignment_9() { return cToCardinalityAssignment_9; }
		
		//Cardinality
		public RuleCall getToCardinalityCardinalityEnumRuleCall_9_0() { return cToCardinalityCardinalityEnumRuleCall_9_0; }
		
		//';'
		public Keyword getSemicolonKeyword_10() { return cSemicolonKeyword_10; }
		
		//'fromElement'
		public Keyword getFromElementKeyword_11() { return cFromElementKeyword_11; }
		
		//':'
		public Keyword getColonKeyword_12() { return cColonKeyword_12; }
		
		//fromElement=ID
		public Assignment getFromElementAssignment_13() { return cFromElementAssignment_13; }
		
		//ID
		public RuleCall getFromElementIDTerminalRuleCall_13_0() { return cFromElementIDTerminalRuleCall_13_0; }
		
		//'from'
		public Keyword getFromKeyword_14() { return cFromKeyword_14; }
		
		//fromRoleName=ID
		public Assignment getFromRoleNameAssignment_15() { return cFromRoleNameAssignment_15; }
		
		//ID
		public RuleCall getFromRoleNameIDTerminalRuleCall_15_0() { return cFromRoleNameIDTerminalRuleCall_15_0; }
		
		//'fromGetElement'
		public Keyword getFromGetElementKeyword_16() { return cFromGetElementKeyword_16; }
		
		//fromGetElement=STRING
		public Assignment getFromGetElementAssignment_17() { return cFromGetElementAssignment_17; }
		
		//STRING
		public RuleCall getFromGetElementSTRINGTerminalRuleCall_17_0() { return cFromGetElementSTRINGTerminalRuleCall_17_0; }
		
		//';'
		public Keyword getSemicolonKeyword_18() { return cSemicolonKeyword_18; }
		
		//'toELement'
		public Keyword getToELementKeyword_19() { return cToELementKeyword_19; }
		
		//':'
		public Keyword getColonKeyword_20() { return cColonKeyword_20; }
		
		//toElement=ID
		public Assignment getToElementAssignment_21() { return cToElementAssignment_21; }
		
		//ID
		public RuleCall getToElementIDTerminalRuleCall_21_0() { return cToElementIDTerminalRuleCall_21_0; }
		
		//'from'
		public Keyword getFromKeyword_22() { return cFromKeyword_22; }
		
		//toRoleName=ID
		public Assignment getToRoleNameAssignment_23() { return cToRoleNameAssignment_23; }
		
		//ID
		public RuleCall getToRoleNameIDTerminalRuleCall_23_0() { return cToRoleNameIDTerminalRuleCall_23_0; }
		
		//'toGetElement'
		public Keyword getToGetElementKeyword_24() { return cToGetElementKeyword_24; }
		
		//toGetElement=STRING
		public Assignment getToGetElementAssignment_25() { return cToGetElementAssignment_25; }
		
		//STRING
		public RuleCall getToGetElementSTRINGTerminalRuleCall_25_0() { return cToGetElementSTRINGTerminalRuleCall_25_0; }
		
		//';'
		public Keyword getSemicolonKeyword_26() { return cSemicolonKeyword_26; }
		
		//('nested' 'mappings' ':' nestedMappings+=NestedMapping* 'end')?
		public Group getGroup_27() { return cGroup_27; }
		
		//'nested'
		public Keyword getNestedKeyword_27_0() { return cNestedKeyword_27_0; }
		
		//'mappings'
		public Keyword getMappingsKeyword_27_1() { return cMappingsKeyword_27_1; }
		
		//':'
		public Keyword getColonKeyword_27_2() { return cColonKeyword_27_2; }
		
		//nestedMappings+=NestedMapping*
		public Assignment getNestedMappingsAssignment_27_3() { return cNestedMappingsAssignment_27_3; }
		
		//NestedMapping
		public RuleCall getNestedMappingsNestedMappingParserRuleCall_27_3_0() { return cNestedMappingsNestedMappingParserRuleCall_27_3_0; }
		
		//'end'
		public Keyword getEndKeyword_27_4() { return cEndKeyword_27_4; }
		
		//('interLanguageMappingEnds' ':' interLanguageMappingEnds+=InterLanguageMappingEnd* 'end')?
		public Group getGroup_28() { return cGroup_28; }
		
		//'interLanguageMappingEnds'
		public Keyword getInterLanguageMappingEndsKeyword_28_0() { return cInterLanguageMappingEndsKeyword_28_0; }
		
		//':'
		public Keyword getColonKeyword_28_1() { return cColonKeyword_28_1; }
		
		//interLanguageMappingEnds+=InterLanguageMappingEnd*
		public Assignment getInterLanguageMappingEndsAssignment_28_2() { return cInterLanguageMappingEndsAssignment_28_2; }
		
		//InterLanguageMappingEnd
		public RuleCall getInterLanguageMappingEndsInterLanguageMappingEndParserRuleCall_28_2_0() { return cInterLanguageMappingEndsInterLanguageMappingEndParserRuleCall_28_2_0; }
		
		//'end'
		public Keyword getEndKeyword_28_3() { return cEndKeyword_28_3; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_29() { return cRightCurlyBracketKeyword_29; }
	}
	public class NestedMappingElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.PerspectiveDSL.NestedMapping");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cNestedKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cMappingKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameIDTerminalRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cColonKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cFromElementKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Keyword cColonKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Keyword cElementNameKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cFromElementNameAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cFromElementNameSTRINGTerminalRuleCall_7_0 = (RuleCall)cFromElementNameAssignment_7.eContents().get(0);
		private final Keyword cFromKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Assignment cFromRoleNameAssignment_9 = (Assignment)cGroup.eContents().get(9);
		private final RuleCall cFromRoleNameIDTerminalRuleCall_9_0 = (RuleCall)cFromRoleNameAssignment_9.eContents().get(0);
		private final Keyword cSemicolonKeyword_10 = (Keyword)cGroup.eContents().get(10);
		private final Keyword cToELementKeyword_11 = (Keyword)cGroup.eContents().get(11);
		private final Keyword cColonKeyword_12 = (Keyword)cGroup.eContents().get(12);
		private final Keyword cElementNameKeyword_13 = (Keyword)cGroup.eContents().get(13);
		private final Assignment cToElementNameAssignment_14 = (Assignment)cGroup.eContents().get(14);
		private final RuleCall cToElementNameSTRINGTerminalRuleCall_14_0 = (RuleCall)cToElementNameAssignment_14.eContents().get(0);
		private final Keyword cFromKeyword_15 = (Keyword)cGroup.eContents().get(15);
		private final Assignment cToRoleNameAssignment_16 = (Assignment)cGroup.eContents().get(16);
		private final RuleCall cToRoleNameIDTerminalRuleCall_16_0 = (RuleCall)cToRoleNameAssignment_16.eContents().get(0);
		private final Keyword cSemicolonKeyword_17 = (Keyword)cGroup.eContents().get(17);
		private final Keyword cEndKeyword_18 = (Keyword)cGroup.eContents().get(18);
		
		//NestedMapping:
		//	'nested' 'mapping' name=ID ':'
		//	'fromElement' ':' 'elementName' fromElementName=STRING 'from' fromRoleName=ID ';'
		//	'toELement' ':' 'elementName' toElementName=STRING 'from' toRoleName=ID ';'
		//	'end';
		@Override public ParserRule getRule() { return rule; }
		
		//'nested' 'mapping' name=ID ':' 'fromElement' ':' 'elementName' fromElementName=STRING 'from' fromRoleName=ID ';'
		//'toELement' ':' 'elementName' toElementName=STRING 'from' toRoleName=ID ';' 'end'
		public Group getGroup() { return cGroup; }
		
		//'nested'
		public Keyword getNestedKeyword_0() { return cNestedKeyword_0; }
		
		//'mapping'
		public Keyword getMappingKeyword_1() { return cMappingKeyword_1; }
		
		//name=ID
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_2_0() { return cNameIDTerminalRuleCall_2_0; }
		
		//':'
		public Keyword getColonKeyword_3() { return cColonKeyword_3; }
		
		//'fromElement'
		public Keyword getFromElementKeyword_4() { return cFromElementKeyword_4; }
		
		//':'
		public Keyword getColonKeyword_5() { return cColonKeyword_5; }
		
		//'elementName'
		public Keyword getElementNameKeyword_6() { return cElementNameKeyword_6; }
		
		//fromElementName=STRING
		public Assignment getFromElementNameAssignment_7() { return cFromElementNameAssignment_7; }
		
		//STRING
		public RuleCall getFromElementNameSTRINGTerminalRuleCall_7_0() { return cFromElementNameSTRINGTerminalRuleCall_7_0; }
		
		//'from'
		public Keyword getFromKeyword_8() { return cFromKeyword_8; }
		
		//fromRoleName=ID
		public Assignment getFromRoleNameAssignment_9() { return cFromRoleNameAssignment_9; }
		
		//ID
		public RuleCall getFromRoleNameIDTerminalRuleCall_9_0() { return cFromRoleNameIDTerminalRuleCall_9_0; }
		
		//';'
		public Keyword getSemicolonKeyword_10() { return cSemicolonKeyword_10; }
		
		//'toELement'
		public Keyword getToELementKeyword_11() { return cToELementKeyword_11; }
		
		//':'
		public Keyword getColonKeyword_12() { return cColonKeyword_12; }
		
		//'elementName'
		public Keyword getElementNameKeyword_13() { return cElementNameKeyword_13; }
		
		//toElementName=STRING
		public Assignment getToElementNameAssignment_14() { return cToElementNameAssignment_14; }
		
		//STRING
		public RuleCall getToElementNameSTRINGTerminalRuleCall_14_0() { return cToElementNameSTRINGTerminalRuleCall_14_0; }
		
		//'from'
		public Keyword getFromKeyword_15() { return cFromKeyword_15; }
		
		//toRoleName=ID
		public Assignment getToRoleNameAssignment_16() { return cToRoleNameAssignment_16; }
		
		//ID
		public RuleCall getToRoleNameIDTerminalRuleCall_16_0() { return cToRoleNameIDTerminalRuleCall_16_0; }
		
		//';'
		public Keyword getSemicolonKeyword_17() { return cSemicolonKeyword_17; }
		
		//'end'
		public Keyword getEndKeyword_18() { return cEndKeyword_18; }
	}
	public class InterLanguageMappingEndElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.PerspectiveDSL.InterLanguageMappingEnd");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cInterKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLanguageKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cMappingKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cEndKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cNameAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cNameIDTerminalRuleCall_4_0 = (RuleCall)cNameAssignment_4.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Keyword cOriginKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Keyword cColonKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cOriginAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final Keyword cOriginSemicolonKeyword_8_0 = (Keyword)cOriginAssignment_8.eContents().get(0);
		private final Keyword cDestinationKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Keyword cColonKeyword_10 = (Keyword)cGroup.eContents().get(10);
		private final Assignment cDestinationAssignment_11 = (Assignment)cGroup.eContents().get(11);
		private final Keyword cDestinationSemicolonKeyword_11_0 = (Keyword)cDestinationAssignment_11.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_12 = (Keyword)cGroup.eContents().get(12);
		
		//InterLanguageMappingEnd:
		//	'inter' 'language' 'mapping' 'end' name=ID '{'
		//	'origin' ':' origin?=';'
		//	'destination' ':' destination?=';'
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'inter' 'language' 'mapping' 'end' name=ID '{' 'origin' ':' origin?=';' 'destination' ':' destination?=';' '}'
		public Group getGroup() { return cGroup; }
		
		//'inter'
		public Keyword getInterKeyword_0() { return cInterKeyword_0; }
		
		//'language'
		public Keyword getLanguageKeyword_1() { return cLanguageKeyword_1; }
		
		//'mapping'
		public Keyword getMappingKeyword_2() { return cMappingKeyword_2; }
		
		//'end'
		public Keyword getEndKeyword_3() { return cEndKeyword_3; }
		
		//name=ID
		public Assignment getNameAssignment_4() { return cNameAssignment_4; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_4_0() { return cNameIDTerminalRuleCall_4_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_5() { return cLeftCurlyBracketKeyword_5; }
		
		//'origin'
		public Keyword getOriginKeyword_6() { return cOriginKeyword_6; }
		
		//':'
		public Keyword getColonKeyword_7() { return cColonKeyword_7; }
		
		//origin?=';'
		public Assignment getOriginAssignment_8() { return cOriginAssignment_8; }
		
		//';'
		public Keyword getOriginSemicolonKeyword_8_0() { return cOriginSemicolonKeyword_8_0; }
		
		//'destination'
		public Keyword getDestinationKeyword_9() { return cDestinationKeyword_9; }
		
		//':'
		public Keyword getColonKeyword_10() { return cColonKeyword_10; }
		
		//destination?=';'
		public Assignment getDestinationAssignment_11() { return cDestinationAssignment_11; }
		
		//';'
		public Keyword getDestinationSemicolonKeyword_11_0() { return cDestinationSemicolonKeyword_11_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_12() { return cRightCurlyBracketKeyword_12; }
	}
	public class ActionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.PerspectiveDSL.Action");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cActionKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cActionTypeAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cActionTypePerspectiveActionTypeEnumRuleCall_1_0 = (RuleCall)cActionTypeAssignment_1.eContents().get(0);
		private final Assignment cRoleNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cRoleNameIDTerminalRuleCall_2_0 = (RuleCall)cRoleNameAssignment_2.eContents().get(0);
		private final Assignment cNameAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cNameSTRINGTerminalRuleCall_3_0 = (RuleCall)cNameAssignment_3.eContents().get(0);
		private final Keyword cSemicolonKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//Action: //   'action' (actionType ?= PerspectiveActionType)?  name = ID';'
		//	'action' actionType=PerspectiveActionType roleName=ID name=STRING ';';
		@Override public ParserRule getRule() { return rule; }
		
		////   'action' (actionType ?= PerspectiveActionType)?  name = ID';'
		//'action' actionType=PerspectiveActionType roleName=ID name=STRING ';'
		public Group getGroup() { return cGroup; }
		
		////   'action' (actionType ?= PerspectiveActionType)?  name = ID';'
		//'action'
		public Keyword getActionKeyword_0() { return cActionKeyword_0; }
		
		//actionType=PerspectiveActionType
		public Assignment getActionTypeAssignment_1() { return cActionTypeAssignment_1; }
		
		//PerspectiveActionType
		public RuleCall getActionTypePerspectiveActionTypeEnumRuleCall_1_0() { return cActionTypePerspectiveActionTypeEnumRuleCall_1_0; }
		
		//roleName=ID
		public Assignment getRoleNameAssignment_2() { return cRoleNameAssignment_2; }
		
		//ID
		public RuleCall getRoleNameIDTerminalRuleCall_2_0() { return cRoleNameIDTerminalRuleCall_2_0; }
		
		//name=STRING
		public Assignment getNameAssignment_3() { return cNameAssignment_3; }
		
		//STRING
		public RuleCall getNameSTRINGTerminalRuleCall_3_0() { return cNameSTRINGTerminalRuleCall_3_0; }
		
		//';'
		public Keyword getSemicolonKeyword_4() { return cSemicolonKeyword_4; }
	}
	public class IntraLanguageMappingElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.PerspectiveDSL.IntraLanguageMapping");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cIntraKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLanguageKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cMappingKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cNameAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cNameIDTerminalRuleCall_3_0 = (RuleCall)cNameAssignment_3.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Keyword cClosureKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Keyword cColonKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cClosureAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final Keyword cClosureSemicolonKeyword_7_0 = (Keyword)cClosureAssignment_7.eContents().get(0);
		private final Keyword cReuseKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Keyword cColonKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Assignment cReuseAssignment_10 = (Assignment)cGroup.eContents().get(10);
		private final Keyword cReuseSemicolonKeyword_10_0 = (Keyword)cReuseAssignment_10.eContents().get(0);
		private final Keyword cIncreaseDepthKeyword_11 = (Keyword)cGroup.eContents().get(11);
		private final Keyword cColonKeyword_12 = (Keyword)cGroup.eContents().get(12);
		private final Assignment cIncreaseDepthAssignment_13 = (Assignment)cGroup.eContents().get(13);
		private final Keyword cIncreaseDepthSemicolonKeyword_13_0 = (Keyword)cIncreaseDepthAssignment_13.eContents().get(0);
		private final Keyword cChangeModelKeyword_14 = (Keyword)cGroup.eContents().get(14);
		private final Keyword cColonKeyword_15 = (Keyword)cGroup.eContents().get(15);
		private final Assignment cChangeModelAssignment_16 = (Assignment)cGroup.eContents().get(16);
		private final Keyword cChangeModelSemicolonKeyword_16_0 = (Keyword)cChangeModelAssignment_16.eContents().get(0);
		private final Keyword cFromElementKeyword_17 = (Keyword)cGroup.eContents().get(17);
		private final Keyword cColonKeyword_18 = (Keyword)cGroup.eContents().get(18);
		private final Assignment cFromElementAssignment_19 = (Assignment)cGroup.eContents().get(19);
		private final RuleCall cFromElementIDTerminalRuleCall_19_0 = (RuleCall)cFromElementAssignment_19.eContents().get(0);
		private final Keyword cFromGetElementKeyword_20 = (Keyword)cGroup.eContents().get(20);
		private final Assignment cFromGetElementAssignment_21 = (Assignment)cGroup.eContents().get(21);
		private final RuleCall cFromGetElementSTRINGTerminalRuleCall_21_0 = (RuleCall)cFromGetElementAssignment_21.eContents().get(0);
		private final Keyword cSemicolonKeyword_22 = (Keyword)cGroup.eContents().get(22);
		private final Keyword cHopsKeyword_23 = (Keyword)cGroup.eContents().get(23);
		private final Keyword cColonKeyword_24 = (Keyword)cGroup.eContents().get(24);
		private final Assignment cHopsAssignment_25 = (Assignment)cGroup.eContents().get(25);
		private final RuleCall cHopsHopParserRuleCall_25_0 = (RuleCall)cHopsAssignment_25.eContents().get(0);
		private final Keyword cEndKeyword_26 = (Keyword)cGroup.eContents().get(26);
		private final Keyword cRightCurlyBracketKeyword_27 = (Keyword)cGroup.eContents().get(27);
		
		//IntraLanguageMapping:
		//	'Intra' 'Language' 'Mapping' name=ID '{'
		//	'closure' ':' closure?=';'
		//	'reuse' ':' reuse?=';'
		//	'increaseDepth' ':' increaseDepth?=';'
		//	'changeModel' ':' changeModel?=';'
		//	'fromElement' ':' fromElement=ID 'fromGetElement' fromGetElement=STRING ';'
		//	'hops' ':'
		//	hops+=Hop*
		//	'end'
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Intra' 'Language' 'Mapping' name=ID '{' 'closure' ':' closure?=';' 'reuse' ':' reuse?=';' 'increaseDepth' ':'
		//increaseDepth?=';' 'changeModel' ':' changeModel?=';' 'fromElement' ':' fromElement=ID 'fromGetElement'
		//fromGetElement=STRING ';' 'hops' ':' hops+=Hop* 'end' '}'
		public Group getGroup() { return cGroup; }
		
		//'Intra'
		public Keyword getIntraKeyword_0() { return cIntraKeyword_0; }
		
		//'Language'
		public Keyword getLanguageKeyword_1() { return cLanguageKeyword_1; }
		
		//'Mapping'
		public Keyword getMappingKeyword_2() { return cMappingKeyword_2; }
		
		//name=ID
		public Assignment getNameAssignment_3() { return cNameAssignment_3; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_3_0() { return cNameIDTerminalRuleCall_3_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_4() { return cLeftCurlyBracketKeyword_4; }
		
		//'closure'
		public Keyword getClosureKeyword_5() { return cClosureKeyword_5; }
		
		//':'
		public Keyword getColonKeyword_6() { return cColonKeyword_6; }
		
		//closure?=';'
		public Assignment getClosureAssignment_7() { return cClosureAssignment_7; }
		
		//';'
		public Keyword getClosureSemicolonKeyword_7_0() { return cClosureSemicolonKeyword_7_0; }
		
		//'reuse'
		public Keyword getReuseKeyword_8() { return cReuseKeyword_8; }
		
		//':'
		public Keyword getColonKeyword_9() { return cColonKeyword_9; }
		
		//reuse?=';'
		public Assignment getReuseAssignment_10() { return cReuseAssignment_10; }
		
		//';'
		public Keyword getReuseSemicolonKeyword_10_0() { return cReuseSemicolonKeyword_10_0; }
		
		//'increaseDepth'
		public Keyword getIncreaseDepthKeyword_11() { return cIncreaseDepthKeyword_11; }
		
		//':'
		public Keyword getColonKeyword_12() { return cColonKeyword_12; }
		
		//increaseDepth?=';'
		public Assignment getIncreaseDepthAssignment_13() { return cIncreaseDepthAssignment_13; }
		
		//';'
		public Keyword getIncreaseDepthSemicolonKeyword_13_0() { return cIncreaseDepthSemicolonKeyword_13_0; }
		
		//'changeModel'
		public Keyword getChangeModelKeyword_14() { return cChangeModelKeyword_14; }
		
		//':'
		public Keyword getColonKeyword_15() { return cColonKeyword_15; }
		
		//changeModel?=';'
		public Assignment getChangeModelAssignment_16() { return cChangeModelAssignment_16; }
		
		//';'
		public Keyword getChangeModelSemicolonKeyword_16_0() { return cChangeModelSemicolonKeyword_16_0; }
		
		//'fromElement'
		public Keyword getFromElementKeyword_17() { return cFromElementKeyword_17; }
		
		//':'
		public Keyword getColonKeyword_18() { return cColonKeyword_18; }
		
		//fromElement=ID
		public Assignment getFromElementAssignment_19() { return cFromElementAssignment_19; }
		
		//ID
		public RuleCall getFromElementIDTerminalRuleCall_19_0() { return cFromElementIDTerminalRuleCall_19_0; }
		
		//'fromGetElement'
		public Keyword getFromGetElementKeyword_20() { return cFromGetElementKeyword_20; }
		
		//fromGetElement=STRING
		public Assignment getFromGetElementAssignment_21() { return cFromGetElementAssignment_21; }
		
		//STRING
		public RuleCall getFromGetElementSTRINGTerminalRuleCall_21_0() { return cFromGetElementSTRINGTerminalRuleCall_21_0; }
		
		//';'
		public Keyword getSemicolonKeyword_22() { return cSemicolonKeyword_22; }
		
		//'hops'
		public Keyword getHopsKeyword_23() { return cHopsKeyword_23; }
		
		//':'
		public Keyword getColonKeyword_24() { return cColonKeyword_24; }
		
		//hops+=Hop*
		public Assignment getHopsAssignment_25() { return cHopsAssignment_25; }
		
		//Hop
		public RuleCall getHopsHopParserRuleCall_25_0() { return cHopsHopParserRuleCall_25_0; }
		
		//'end'
		public Keyword getEndKeyword_26() { return cEndKeyword_26; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_27() { return cRightCurlyBracketKeyword_27; }
	}
	public class HopElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.PerspectiveDSL.Hop");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHopElementKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cColonKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cHopElementAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cHopElementIDTerminalRuleCall_2_0 = (RuleCall)cHopElementAssignment_2.eContents().get(0);
		private final Keyword cFromGetHopKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cFromGetHopAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cFromGetHopSTRINGTerminalRuleCall_4_0 = (RuleCall)cFromGetHopAssignment_4.eContents().get(0);
		private final Keyword cSemicolonKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Hop:
		//	'hopElement' ':' hopElement=ID 'fromGetHop' fromGetHop=STRING ';';
		@Override public ParserRule getRule() { return rule; }
		
		//'hopElement' ':' hopElement=ID 'fromGetHop' fromGetHop=STRING ';'
		public Group getGroup() { return cGroup; }
		
		//'hopElement'
		public Keyword getHopElementKeyword_0() { return cHopElementKeyword_0; }
		
		//':'
		public Keyword getColonKeyword_1() { return cColonKeyword_1; }
		
		//hopElement=ID
		public Assignment getHopElementAssignment_2() { return cHopElementAssignment_2; }
		
		//ID
		public RuleCall getHopElementIDTerminalRuleCall_2_0() { return cHopElementIDTerminalRuleCall_2_0; }
		
		//'fromGetHop'
		public Keyword getFromGetHopKeyword_3() { return cFromGetHopKeyword_3; }
		
		//fromGetHop=STRING
		public Assignment getFromGetHopAssignment_4() { return cFromGetHopAssignment_4; }
		
		//STRING
		public RuleCall getFromGetHopSTRINGTerminalRuleCall_4_0() { return cFromGetHopSTRINGTerminalRuleCall_4_0; }
		
		//';'
		public Keyword getSemicolonKeyword_5() { return cSemicolonKeyword_5; }
	}
	
	public class CardinalityElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.PerspectiveDSL.Cardinality");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cCOMPULSORYEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cCOMPULSORY1Keyword_0_0 = (Keyword)cCOMPULSORYEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cOPTIONALEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cOPTIONAL01Keyword_1_0 = (Keyword)cOPTIONALEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cCOMPULSORY_MULTIPLEEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cCOMPULSORY_MULTIPLE1Keyword_2_0 = (Keyword)cCOMPULSORY_MULTIPLEEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cOPTIONAL_MULTIPLEEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cOPTIONAL_MULTIPLE0Keyword_3_0 = (Keyword)cOPTIONAL_MULTIPLEEnumLiteralDeclaration_3.eContents().get(0);
		
		//enum Cardinality:
		//	COMPULSORY='1' | OPTIONAL='0..1' | COMPULSORY_MULTIPLE='1..*' | OPTIONAL_MULTIPLE='0..*';
		public EnumRule getRule() { return rule; }
		
		//COMPULSORY='1' | OPTIONAL='0..1' | COMPULSORY_MULTIPLE='1..*' | OPTIONAL_MULTIPLE='0..*'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//COMPULSORY='1'
		public EnumLiteralDeclaration getCOMPULSORYEnumLiteralDeclaration_0() { return cCOMPULSORYEnumLiteralDeclaration_0; }
		
		//'1'
		public Keyword getCOMPULSORY1Keyword_0_0() { return cCOMPULSORY1Keyword_0_0; }
		
		//OPTIONAL='0..1'
		public EnumLiteralDeclaration getOPTIONALEnumLiteralDeclaration_1() { return cOPTIONALEnumLiteralDeclaration_1; }
		
		//'0..1'
		public Keyword getOPTIONAL01Keyword_1_0() { return cOPTIONAL01Keyword_1_0; }
		
		//COMPULSORY_MULTIPLE='1..*'
		public EnumLiteralDeclaration getCOMPULSORY_MULTIPLEEnumLiteralDeclaration_2() { return cCOMPULSORY_MULTIPLEEnumLiteralDeclaration_2; }
		
		//'1..*'
		public Keyword getCOMPULSORY_MULTIPLE1Keyword_2_0() { return cCOMPULSORY_MULTIPLE1Keyword_2_0; }
		
		//OPTIONAL_MULTIPLE='0..*'
		public EnumLiteralDeclaration getOPTIONAL_MULTIPLEEnumLiteralDeclaration_3() { return cOPTIONAL_MULTIPLEEnumLiteralDeclaration_3; }
		
		//'0..*'
		public Keyword getOPTIONAL_MULTIPLE0Keyword_3_0() { return cOPTIONAL_MULTIPLE0Keyword_3_0; }
	}
	public class PerspectiveActionTypeElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.PerspectiveDSL.PerspectiveActionType");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cREEXPOSEEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cREEXPOSERe_exposeKeyword_0_0 = (Keyword)cREEXPOSEEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cREDEFINEDEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cREDEFINEDRedefinedKeyword_1_0 = (Keyword)cREDEFINEDEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cCREATE_MAPPINGEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cCREATE_MAPPINGCreate_mappingKeyword_2_0 = (Keyword)cCREATE_MAPPINGEnumLiteralDeclaration_2.eContents().get(0);
		
		//enum PerspectiveActionType:
		//	REEXPOSE='re_expose' | REDEFINED='redefined' | CREATE_MAPPING='create_mapping';
		public EnumRule getRule() { return rule; }
		
		//REEXPOSE='re_expose' | REDEFINED='redefined' | CREATE_MAPPING='create_mapping'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//REEXPOSE='re_expose'
		public EnumLiteralDeclaration getREEXPOSEEnumLiteralDeclaration_0() { return cREEXPOSEEnumLiteralDeclaration_0; }
		
		//'re_expose'
		public Keyword getREEXPOSERe_exposeKeyword_0_0() { return cREEXPOSERe_exposeKeyword_0_0; }
		
		//REDEFINED='redefined'
		public EnumLiteralDeclaration getREDEFINEDEnumLiteralDeclaration_1() { return cREDEFINEDEnumLiteralDeclaration_1; }
		
		//'redefined'
		public Keyword getREDEFINEDRedefinedKeyword_1_0() { return cREDEFINEDRedefinedKeyword_1_0; }
		
		//CREATE_MAPPING='create_mapping'
		public EnumLiteralDeclaration getCREATE_MAPPINGEnumLiteralDeclaration_2() { return cCREATE_MAPPINGEnumLiteralDeclaration_2; }
		
		//'create_mapping'
		public Keyword getCREATE_MAPPINGCreate_mappingKeyword_2_0() { return cCREATE_MAPPINGCreate_mappingKeyword_2_0; }
	}
	
	private final PerspectiveModelElements pPerspectiveModel;
	private final PerspectiveElements pPerspective;
	private final LanguageElements pLanguage;
	private final LanguageElementMappingElements pLanguageElementMapping;
	private final NestedMappingElements pNestedMapping;
	private final InterLanguageMappingEndElements pInterLanguageMappingEnd;
	private final ActionElements pAction;
	private final IntraLanguageMappingElements pIntraLanguageMapping;
	private final HopElements pHop;
	private final CardinalityElements eCardinality;
	private final PerspectiveActionTypeElements ePerspectiveActionType;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public PerspectiveDSLGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pPerspectiveModel = new PerspectiveModelElements();
		this.pPerspective = new PerspectiveElements();
		this.pLanguage = new LanguageElements();
		this.pLanguageElementMapping = new LanguageElementMappingElements();
		this.pNestedMapping = new NestedMappingElements();
		this.pInterLanguageMappingEnd = new InterLanguageMappingEndElements();
		this.pAction = new ActionElements();
		this.pIntraLanguageMapping = new IntraLanguageMappingElements();
		this.pHop = new HopElements();
		this.eCardinality = new CardinalityElements();
		this.ePerspectiveActionType = new PerspectiveActionTypeElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.PerspectiveDSL".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//PerspectiveModel:
	//	perspective+=Perspective*;
	public PerspectiveModelElements getPerspectiveModelAccess() {
		return pPerspectiveModel;
	}
	
	public ParserRule getPerspectiveModelRule() {
		return getPerspectiveModelAccess().getRule();
	}
	
	//Perspective:
	//	'perspective' name=ID '{' ('default' default=ID ';')?
	//	'display' 'name' displayName=STRING ';'
	//	'languages' ':'
	//	languages+=Language*
	//	'end'
	//	'actions' ':'
	//	actions+=Action*
	//	'end'
	//	'mappings' ':'
	//	mappings+=LanguageElementMapping*
	//	'end' ('intraLanguageMappings' ':'
	//	intralanguagemappings+=IntraLanguageMapping*)?
	//	'end'
	//	'}';
	public PerspectiveElements getPerspectiveAccess() {
		return pPerspective;
	}
	
	public ParserRule getPerspectiveRule() {
		return getPerspectiveAccess().getRule();
	}
	
	//Language:
	//	'existing' 'language' name=ID '{'
	//	"rootPackage" rootPackage=STRING ';'
	//	"packageClassName" packageClassName=ID ';'
	//	"roleName" roleName=ID ';'
	//	'}';
	public LanguageElements getLanguageAccess() {
		return pLanguage;
	}
	
	public ParserRule getLanguageRule() {
		return getLanguageAccess().getRule();
	}
	
	//LanguageElementMapping:
	//	'mapping' name=ID '{'
	//	//        'relationship' ':' relationship = Relationship';'
	//	'fromCardinality' ':' fromCardinality=Cardinality ';'
	//	'toCardinality' ':' toCardinality=Cardinality ';'
	//	'fromElement' ':' fromElement=ID 'from' fromRoleName=ID 'fromGetElement' fromGetElement=STRING ';'
	//	'toELement' ':' toElement=ID 'from' toRoleName=ID 'toGetElement' toGetElement=STRING ';' ('nested' 'mappings' ':'
	//	nestedMappings+=NestedMapping*
	//	'end')? ('interLanguageMappingEnds' ':'
	//	interLanguageMappingEnds+=InterLanguageMappingEnd*
	//	'end')?
	//	'}';
	public LanguageElementMappingElements getLanguageElementMappingAccess() {
		return pLanguageElementMapping;
	}
	
	public ParserRule getLanguageElementMappingRule() {
		return getLanguageElementMappingAccess().getRule();
	}
	
	//NestedMapping:
	//	'nested' 'mapping' name=ID ':'
	//	'fromElement' ':' 'elementName' fromElementName=STRING 'from' fromRoleName=ID ';'
	//	'toELement' ':' 'elementName' toElementName=STRING 'from' toRoleName=ID ';'
	//	'end';
	public NestedMappingElements getNestedMappingAccess() {
		return pNestedMapping;
	}
	
	public ParserRule getNestedMappingRule() {
		return getNestedMappingAccess().getRule();
	}
	
	//InterLanguageMappingEnd:
	//	'inter' 'language' 'mapping' 'end' name=ID '{'
	//	'origin' ':' origin?=';'
	//	'destination' ':' destination?=';'
	//	'}';
	public InterLanguageMappingEndElements getInterLanguageMappingEndAccess() {
		return pInterLanguageMappingEnd;
	}
	
	public ParserRule getInterLanguageMappingEndRule() {
		return getInterLanguageMappingEndAccess().getRule();
	}
	
	//Action: //   'action' (actionType ?= PerspectiveActionType)?  name = ID';'
	//	'action' actionType=PerspectiveActionType roleName=ID name=STRING ';';
	public ActionElements getActionAccess() {
		return pAction;
	}
	
	public ParserRule getActionRule() {
		return getActionAccess().getRule();
	}
	
	//IntraLanguageMapping:
	//	'Intra' 'Language' 'Mapping' name=ID '{'
	//	'closure' ':' closure?=';'
	//	'reuse' ':' reuse?=';'
	//	'increaseDepth' ':' increaseDepth?=';'
	//	'changeModel' ':' changeModel?=';'
	//	'fromElement' ':' fromElement=ID 'fromGetElement' fromGetElement=STRING ';'
	//	'hops' ':'
	//	hops+=Hop*
	//	'end'
	//	'}';
	public IntraLanguageMappingElements getIntraLanguageMappingAccess() {
		return pIntraLanguageMapping;
	}
	
	public ParserRule getIntraLanguageMappingRule() {
		return getIntraLanguageMappingAccess().getRule();
	}
	
	//Hop:
	//	'hopElement' ':' hopElement=ID 'fromGetHop' fromGetHop=STRING ';';
	public HopElements getHopAccess() {
		return pHop;
	}
	
	public ParserRule getHopRule() {
		return getHopAccess().getRule();
	}
	
	//enum Cardinality:
	//	COMPULSORY='1' | OPTIONAL='0..1' | COMPULSORY_MULTIPLE='1..*' | OPTIONAL_MULTIPLE='0..*';
	public CardinalityElements getCardinalityAccess() {
		return eCardinality;
	}
	
	public EnumRule getCardinalityRule() {
		return getCardinalityAccess().getRule();
	}
	
	//enum PerspectiveActionType:
	//	REEXPOSE='re_expose' | REDEFINED='redefined' | CREATE_MAPPING='create_mapping';
	public PerspectiveActionTypeElements getPerspectiveActionTypeAccess() {
		return ePerspectiveActionType;
	}
	
	public EnumRule getPerspectiveActionTypeRule() {
		return getPerspectiveActionTypeAccess().getRule();
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' |
	//	"'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/*'->'*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
