/*
 * generated by Xtext 2.22.0
 */
package ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.perspectivedsl.ui.internal.PerspectivedslActivator;

public class PerspectiveDSLUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return PerspectivedslActivator.getInstance().getInjector("ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.PerspectiveDSL");
	}

}
